import { Vocabulary } from "../types/types.ts";

const vocabularyArray3: Vocabulary[] = [
  {label: "switch", bold: false, explain: "v. 改变，转变；转移"},
  {label: "change", bold: false, explain: "v./n. 改变，变化"},
  {label: "alter", bold: false, explain: "v. 改变"},
  {label: "vary", bold: false, explain: "v. 变化"},
  {label: "turn", bold: false, explain: "v. 改变，转变"},
  {label: "transform", bold: false, explain: "vt. 使改变"},
  {label: "convert", bold: false, explain: "vt. 改变，转换"},
  {label: "reduce", bold: true, explain: "vt. 缩小，减小，减低"},
  {label: "shorten", bold: false, explain: "vt. 缩短；减少；变短"},
  {label: "decrease", bold: false, explain: "v. 减少，降低"},
  {label: "lessen", bold: false, explain: "v. 减少，降低"},
  {label: "cut down", bold: false, explain: "减少"},
  {label: "amplify", bold: true, explain: "vt. 扩大，放大，增强"},
  {label: "magnify", bold: false, explain: "vt. 放大；扩大"},
  {label: "broaden", bold: false, explain: "v. 变宽；变阔"},
  {label: "extend", bold: false, explain: "v. 扩大；延长"},
  {label: "enlarge", bold: false, explain: "v. 扩大；扩充"},
  {label: "expand", bold: false, explain: "v. 扩大；增加"},
  {label: "raise", bold: true, explain: "vt. 提高；举起；增加；筹集；抚养"},
  {label: "elevate", bold: false, explain: "vt. 提升；提高；抬起"},
  {label: "increase", bold: false, explain: "v. 增长，增多"},
  {label: "lift", bold: false, explain: "v. 举起；提起；抬高"},
  {label: "boost", bold: false, explain: "v. 使增长，推动"},
  {label: "enhance", bold: false, explain: "v. 增强，提高，改善"},
  { label: "drop", bold: false, explain: "v. 下降" },
  { label: "lower", bold: false, explain: "v. 减少；缩小" },
  { label: "fall", bold: false, explain: "v. 落下；跌倒" },
  { label: "decline", bold: false, explain: "v. 下降；减少" },
  { label: "dive", bold: false, explain: "v. 骤降，突然暴跌" },
  { label: "diminish", bold: false, explain: "v. 减少，降低" },
  { label: "bewilder", bold: true, explain: "vt. 使迷惑；使糊涂" },
  { label: "puzzle", bold: false, explain: "vt. 使迷惑" },
  { label: "confuse", bold: false, explain: "vt. 使糊涂；混淆" },
  { label: "arouse", bold: true, explain: "vt. 激起；唤起" },
  { label: "excite", bold: false, explain: "vt. 使激动；使兴奋" },
  { label: "stimulate", bold: false, explain: "vt. 激发；激励" },
  { label: "provoke", bold: false, explain: "vt. 激起；引起" },
  { label: "rouse", bold: false, explain: "vt. 激起；唤起" },
  { label: "set off", bold: true, explain: "引起；使爆炸" },
  { label: "cause", bold: false, explain: "vt. 引起" },
  { label: "bring about", bold: false, explain: "引起" },
  { label: "give rise to", bold: false, explain: "引起，导致" },
  { label: "attain", bold: true, explain: "v. 获得" },
  { label: "gain", bold: false, explain: "v. 获得；赢得；博得" },
  { label: "obtain", bold: false, explain: "v. 获得；赢得" },
  { label: "earn", bold: false, explain: "v. 赢得；博得" },
  { label: "acquire", bold: false, explain: "vt. 获得；得到" },
  { label: "cease", bold: true, explain: "vi. 停止，中止" },
  { label: "stop", bold: false, explain: "v./n. 停止" },
  { label: "end", bold: false, explain: "v./n. 终止，终结" },
  { label: "halt", bold: false, explain: "n. 停止；阻止；暂停" },
  { label: "quit", bold: false, explain: "v. 停止；退出；戒掉" },
  { label: "culminate", bold: false, explain: "vt. (以……)结束" },
  { label: "terminate", bold: false, explain: "v. 终止；停止" },
  { label: "accomplish", bold: true, explain: "v. 完成，实现" },
  { label: "achieve", bold: false, explain: "v. 达到，取得，实现" },
  { label: "fulfill", bold: false, explain: "vt. 履行；实现" },
  { label: "finish", bold: false, explain: "v. 完成，做好" },
  { label: "complete", bold: false, explain: "v. 完成；使完整" },
  { label: "conceal", bold: true, explain: "vt. 隐藏" },
  { label: "hide", bold: false, explain: "v. 隐藏" },
  { label: "mask", bold: false, explain: "v. 掩饰，遮盖" },
  { label: "request", bold: true, explain: "n.vt. 请求，要求" },
  { label: "require", bold: false, explain: "vt. 要求；需要" },
  { label: "want", bold: false, explain: "v. 希望；想要；要" },
  { label: "claim", bold: false, explain: "vt. 要求；声称；需要" },
  { label: "demand", bold: false, explain: "v./n. 需要；要求" },
  { label: "ask", bold: false, explain: "v. 问;询问;要求;请求" },
  { label: "call for", bold: false, explain: "要求;需要" },
  { label: "denote", bold: true, explain: "vt. 表示;标志;预示;象征" },
  { label: "express", bold: false, explain: "vt. 表示;表露;表达" },
  { label: "indicate", bold: false, explain: "v. 表明;显示;象征" },
  { label: "signify", bold: false, explain: "v. 表示;说明;预示" },
  { label: "imply", bold: false, explain: "v. 暗示;表明" },
  { label: "show", bold: false, explain: "v. 显示;表明;展示" },
  { label: "compose", bold: true, explain: "vt. 由...组成;作曲" },
  { label: "constitute", bold: false, explain: "v. 构成,组成" },
  { label: "comprise", bold: false, explain: "v. 包含;由...组成" },
  { label: "consist", bold: false, explain: "v. 由...组成" },
  { label: "make up", bold: false, explain: "组成;化妆;编造" },
  { label: "blend", bold: true, explain: "v/n. 混合" },
  { label: "combine", bold: false, explain: "v. 结合,联合" },
  { label: "mix", bold: false, explain: "v. (使)混合" },
  { label: "mingle", bold: false, explain: "v. (使)混合" },
  { label: "adapt", bold: true, explain: "vt. 调整,使适应,改编" },
  { label: "adjust", bold: false, explain: "v. 调整;调节" },
  { label: "change", bold: false, explain: "v. 改变;变化" },
  { label: "alter", bold: false, explain: "v. 改变;更改" },
  { label: "modify", bold: false, explain: "vt. 修改;修饰" },
  { label: "switch", bold: false, explain: "v. 转换；交换" },
  { label: "exchange", bold: false, explain: "v./n. 交换" },
  { label: "divert", bold: true, explain: "vt. 转移；使...转向 vt. 转移" },
  { label: "shift", bold: false, explain: "v. 转移；挪动" },
  { label: "transfer", bold: false, explain: "v. 转移；搬迁" },
  { label: "distract", bold: false, explain: "vt. 分散；转移" },
  { label: "duplicate", bold: true, explain: "vt. 复制 n. 复制品" },
  { label: "copy", bold: false, explain: "v. 复制；复印；模仿" },
  { label: "reproduce", bold: false, explain: "v. 复制；再现" },
  { label: "repeat", bold: false, explain: "v. 重复；重说；重写" },
  { label: "eliminate", bold: true, explain: "vt. 排除，消除" },
  { label: "eradicate", bold: false, explain: "vt. 根除；消灭" },
  { label: "exclude", bold: false, explain: "vt. 排除；不包括" },
  { label: "get rid of", bold: false, explain: "摆脱；丢弃" },
  { label: "remove", bold: false, explain: "vt. 去除；去掉；移开" },
  { label: "dismiss", bold: false, explain: "vt. 不予考虑；摒弃" },
  { label: "determine", bold: true, explain: "vt. 决定，决心" },
  { label: "resolve", bold: false, explain: "v. 决定；决心" },
  { label: "make up one’s mind", bold: false, explain: "下定决心" },
  { label: "discharge", bold: true, explain: "vt. 释放，排出 n. 释放" },
  { label: "expel", bold: true, explain: "vt. 驱逐；排出" },
  { label: "release", bold: true, explain: "vt. 释放；放出；放走" },
  { label: "free", bold: true, explain: "v. 释放；使解脱出来" },
  { label: "liberate", bold: true, explain: "v. 解放；释放" },
  { label: "hinder", bold: true, explain: "v. 阻碍，妨碍" },
  { label: "curb", bold: true, explain: "vt. 遏制；控制，抑制" },
  { label: "handicap", bold: true, explain: "vt. 阻碍；使不利" },
  { label: "obstruct", bold: true, explain: "vt. 阻碍；阻挡" },
  { label: "restrain", bold: true, explain: "vt. 制止，阻止" },
  { label: "block", bold: true, explain: "vt. 阻碍；堵塞；阻塞" },
  { label: "stop", bold: true, explain: "v. 停止；(使)停下" },
  { label: "hold back", bold: true, explain: "阻止；阻挡；克制" },
  { label: "barrier", bold: true, explain: "n. 障碍；屏障；阻力" },
  { label: "flee", bold: true, explain: "v. 逃离，逃避" },
  { label: "dodge", bold: true, explain: "v. 闪开，躲开；逃避" },
  { label: "escape", bold: true, explain: "v. 逃脱；逃避" },
  { label: "evade", bold: true, explain: "v. 规避，逃避" },
  { label: "retreat", bold: true, explain: "v. 撤退；后退" }

]
export default vocabularyArray3
