import {Vocabulary} from "@/types/types.ts";

const vocabularyArray4: Vocabulary[] = [
    { label: "emotion", bold: false, explain: "n. 感情，情绪，情感" },
    { label: "affection", bold: true, explain: "n. 感情；喜爱" },
    { label: "feeling", bold: true, explain: "n. 感觉；感触" },
    { label: "sentiment", bold: true, explain: "n. 情绪；看法" },
    { label: "mood", bold: true, explain: "n. 情绪；心情；气氛" },
    { label: "affect", bold: true, explain: "vt. 影响；感动；侵袭" },
    { label: "influence", bold: true, explain: "v./n. 影响；作用" },
    { label: "impact", bold: true, explain: "v./n. 影响；撞击" },
    { label: "have an impact on", bold: true, explain: "对...有影响" },
    { label: "flood", bold: true, explain: "v. (使) 淹没；泛滥 n. 洪水，水灾" },
    { label: "overwhelm", bold: true, explain: "vt. 淹没；压倒" },
    { label: "drown", bold: true, explain: "v. 浸透；淹死，溺死" },
    { label: "swallow", bold: true, explain: "v. 吞没，淹没" },
    { label: "submerge", bold: true, explain: "v. 淹没" },
    { label: "adore", bold: true, explain: "v. 崇拜,热爱" },
    { label: "admire", bold: true, explain: "vt. 钦佩；欣赏" },
    { label: "worship", bold: true, explain: "v./n. 崇拜，敬仰" },
    { label: "stress", bold: true, explain: "n. 压力；紧迫；强调 vt. 强调" },
    { label: "combat with", bold: false, explain: "v. 与...战斗；反对" },
    { label: "combat", bold: true, explain: "n. 战斗，搏斗 vt. 与...战斗；反对" },
    { label: "battle", bold: false, explain: "n. 战斗，搏斗 v. 与...作战" },
    { label: "conflict", bold: false, explain: "n. 战斗 v. 冲突" },
    { label: "fight", bold: false, explain: "n. 搏斗；打架 v. 与...作斗争" },
    { label: "war", bold: false, explain: "n. 战争 vi. 进行战斗；作战" },
    { label: "opponent", bold: true, explain: "n. 对手，敌手" },
    { label: "rival", bold: false, explain: "n. 竞争对手" },
    { label: "competitor", bold: false, explain: "n. 竞争对手" },
    { label: "enemy", bold: false, explain: "n. 敌人；仇人" },
    { label: "civilian", bold: true, explain: "n. 平民，百姓 adj. 平民的，民间的" },
    { label: "people", bold: false, explain: "n. 人；人们；人民" },
    { label: "citizen", bold: false, explain: "n. 公民；市民；老百姓" },
    { label: "civil", bold: false, explain: "adj. 公民的；国民的；平民的" },
    { label: "folk", bold: false, explain: "n. 人们；家人" },
    { label: "chaos", bold: true, explain: "n. 混沌，混乱" },
    { label: "riot", bold: false, explain: "n.v. 骚乱，闹事" },
    { label: "disorder", bold: false, explain: "n. 混乱；紊乱" },
    { label: "turbulence", bold: false, explain: "n. 动荡；骚乱" },
    { label: "mess", bold: false, explain: "n. 混乱；杂乱；肮脏" },
    { label: "oppose", bold: true, explain: "vt. 反对；抵制" },
    { label: "refuse", bold: false, explain: "v. 拒绝；回绝" },
    { label: "disagree", bold: false, explain: "v. 反对；不同意" },
    { label: "object", bold: false, explain: "v. 反对；不同意" },
    { label: "disapprove", bold: false, explain: "v. 反对；不同意" },
    { label: "rebel", bold: true, explain: "vi. 反抗，起义 n. 叛逆者，起义者" },
    { label: "revolt", bold: true, explain: "v. 反抗；起义；叛乱" },
    { label: "uprising", bold: false, explain: "n. 起义；造反" },
    { label: "surrender", bold: true, explain: "vi. 投降；屈服，让步 vt. 交出，放弃" },
    { label: "submit", bold: false, explain: "vt. 屈服；提交；呈递" },
    { label: "yield", bold: false, explain: "vi. 屈服；放弃；产生" },
    { label: "capitulate", bold: false, explain: "vi. 屈服；屈从" },
    { label: "give up", bold: false, explain: "放弃；认输" },
    { label: "condemn", bold: true, explain: "vt. 谴责；指责；宣判，判刑" },
    { label: "blame", bold: false, explain: "vt. 责备；责怪；指责" },
    { label: "accuse", bold: false, explain: "vt. 指责，谴责；控告" },
    { label: "find fault with", bold: false, explain: "挑剔；找茬儿；指责" },
    { label: "denounce", bold: false, explain: "vt. 谴责；指责" },
    { label: "criticize", bold: false, explain: "v. 批评；批判；挑剔" },
    { label: "appeal", bold: true, explain: "vi./n. 恳求,请求;呼吁" },
    { label: "plead", bold: false, explain: "v. 申辩;恳求;乞求" },
    { label: "implore", bold: false, explain: "v. 恳求;哀求" },
    { label: "pray", bold: false, explain: "v. 恳求;祈祷" },
    { label: "request", bold: false, explain: "n.vt. 请求,要求" },
    { label: "conquer", bold: true, explain: "vt. 战胜,征服" },
    { label: "win", bold: false, explain: "v. 赢;获胜" },
    { label: "defeat", bold: false, explain: "vt. 战胜;击败" },
    { label: "overcome", bold: false, explain: "vt. 克服;战胜" },
    { label: "triumph", bold: false, explain: "vi. 成功;战胜;报复" },
    { label: "dominate", bold: true, explain: "vt. 控制,统治,支配" },
    { label: "govern", bold: false, explain: "v. 控制;统治;管理" },
    { label: "control", bold: false, explain: "vt. 控制;指挥;尊重" },
    { label: "rule", bold: false, explain: "v. 控制;统治;支配" },
    { label: "reign", bold: false, explain: "vi. 统治;当政;为王" },
    { label: "administrate", bold: false, explain: "v. 管理,支配" },
    { label: "curb", bold: false, explain: "v. 控制,抑制" },
    { label: "damage", bold: true, explain: "vt. 损害,毁坏 n. 损害" },
    { label: "destroy", bold: false, explain: "vt. 摧毁;毁灭;破坏" },
    { label: "ruin", bold: false, explain: "vt. 破坏;毁灭;毁坏" },
    { label: "break", bold: false, explain: "v. 打破;(使)破,裂,碎" },
    { label: "destruct", bold: false, explain: "adj. 破坏的 vi. 破坏" },
    { label: "shatter", bold: false, explain: "v. 摧毁,粉碎" },
    { label: "aggressive", bold: false, explain: "adj. 好斗的,进攻的" },
    { label: "militant", bold: true, explain: "adj. 激进的；好斗的" },
    { label: "attacking", bold: true, explain: "adj. 攻击性的" },
    { label: "disclose", bold: true, explain: "v. 揭露，透露" },
    { label: "reveal", bold: true, explain: "vt. 揭露，展现；告诉" },
    { label: "expose", bold: true, explain: "vt. 揭露，暴露" },
    { label: "uncover", bold: true, explain: "vt. 揭露；发现" },
    { label: "give out", bold: true, explain: "公开，宣布" },
    { label: "confidential", bold: true, explain: "adj. 秘密的" },
    { label: "secret", bold: true, explain: "adj. 秘密的 n. 秘密；秘诀" },
    { label: "underground", bold: true, explain: "adj. 秘密的" },
    { label: "private", bold: true, explain: "adj. 私下的；秘密的" },
    { label: "backdoor", bold: true, explain: "adj. 秘密的" },
    { label: "recipe", bold: true, explain: "n. 食谱；秘诀；秘方" },
    { label: "law", bold: true, explain: "n. 法律，法规；规律，法则，定律" },
    { label: "decree", bold: true, explain: "n. 法令；政令" },
    { label: "code", bold: true, explain: "n. 法典，法规，章程；密码" },
    { label: "regulation", bold: true, explain: "n. 规章制度" },
    { label: "commission", bold: true, explain: "n. 委员会" },
    { label: "board", bold: false, explain: "n. 委员会, 理事会" },
    { label: "council", bold: false, explain: "n. 委员会" },
    { label: "delegation", bold: false, explain: "n. 代表团; 委托" },
    { label: "committee", bold: false, explain: "n. 委员会" },
    { label: "department", bold: true, explain: "n. 部, 司, 局, 处, 系" },
    { label: "ministry", bold: false, explain: "n. 部" },
    { label: "division", bold: false, explain: "n. 部门; 级; 师" },
    { label: "bureau", bold: false, explain: "n. 办事处; 处; 科" },
    { label: "sector", bold: false, explain: "n. 部门, 领域; 行业" },
    { label: "perform", bold: true, explain: "vt. 施行, 完成" },
    { label: "fulfil", bold: false, explain: "v. 履行, 执行" },
    { label: "implement", bold: false, explain: "vt. 实施, 贯彻" },
    { label: "execute", bold: false, explain: "vt. 实行; 实施" },
    { label: "conduct", bold: false, explain: "v. 实施; 执行" },
    { label: "carry out", bold: false, explain: "实施; 执行; 实行" },
    { label: "inquiry", bold: true, explain: "n. 调查; 质询" },
    { label: "investigation", bold: false, explain: "n. 调查; 研究" },
    { label: "survey", bold: false, explain: "n. 调查" },
    { label: "research", bold: false, explain: "n.vt. 研究; 调查" },
    { label: "inspect", bold: false, explain: "vt. 检查; 查看" },
    { label: "examine", bold: false, explain: "vt. 检查; 考察" },
    { label: "illegal", bold: true, explain: "adj. 非法的, 不合法的" },
    { label: 'illicit', bold: false, explain: "非法的；违法的" },
    { label: "legitimate", bold: true, explain: "adj. 合法的；合理的" },
    { label: "legal", bold: false, explain: "adj. 合法的；法律的" },
    { label: "lawful", bold: false, explain: "adj. 法定的；法律承认的" },
    { label: "valid", bold: false, explain: "adj. 合法有效的；认可的" },
    { label: "rightful", bold: false, explain: "adj. 合法的；公正的" },
    { label: "deceive", bold: true, explain: "vt. 欺骗，蒙蔽" },
    { label: "cheat", bold: false, explain: "v. 欺骗；蒙骗" },
    { label: "lie", bold: false, explain: "v. 说谎；撒谎" },
    { label: "trick", bold: false, explain: "vt. 欺骗；欺诈" },
    { label: "fraud", bold: false, explain: "n. 欺诈；欺诈罪；骗子" },
    { label: "standard", bold: true, explain: "n. 标准；准则；准据" },
    { label: "criterion", bold: false, explain: "n. 标准；准则" },
    { label: "rule", bold: false, explain: "n. 规则；准则；条例" },
    { label: "guideline", bold: false, explain: "n. 准则；指南" },
    { label: "norm", bold: false, explain: "n. 标准；准则" },
    { label: "innocent", bold: true, explain: "adj. 无罪的，清白的；天真的" },
    { label: "blameless", bold: false, explain: "adj. 无过错的" },
    { label: "faultless", bold: false, explain: "adj. 没有错误的" },
    { label: "guiltless", bold: false, explain: "adj. 无辜的；无罪的" },
    { label: "sinless", bold: false, explain: "adj. 无罪；无罪的" }
]
vocabularyArray4.forEach(item => {
    item.bold = false
})
export default vocabularyArray4
