import {Vocabulary} from "@/types/types.ts";

const vocabularyArray5: Vocabulary[] = [
  { label: 'pledge', bold: false, explain: '誓言，承诺' },
  { label: 'promise', bold: true, explain: '' },
  { label: 'pose', bold: true, explain: '提出，引起' },
  { label: 'raise', bold: true, explain: '提出，提高' },
  { label: 'poverty', bold: true, explain: '贫困' },
  { label: 'needy', bold: true, explain: '贫困的' },
  { label: 'impoverish', bold: false, explain: '使贫困' },
  { label: 'practice', bold: false, explain: '实践，练习' },
  { label: 'practicality', bold: true, explain: '实用性，实际性' },
  { label: 'precious', bold: true, explain: '珍贵的' },
  { label: 'valuable', bold: false, explain: '有价值的' },
  { label: 'precision', bold: true, explain: '精度，精确度' },
  { label: 'accuracy', bold: true, explain: '准确性，准确度' },
  { label: 'predict', bold: true, explain: '预测，预言' },
  { label: 'foreseen', bold: true, explain: '预见，预料' },
  { label: 'forecast', bold: true, explain: '预报' },
  { label: 'present', bold: true, explain: '礼物、呈现、目前的' },
  { label: 'pressing', bold: true, explain: '紧迫的，急迫的' },
  { label: 'urgent', bold: true, explain: '紧急的，急迫的' },
  { label: 'presume', bold: true, explain: '假设，推测' },
  { label: 'assume', bold: true, explain: '假定，假设' },
  { label: 'suppose', bold: true, explain: '假定的，应该是' },
  { label: 'imagine', bold: false, explain: '想像，设想' },
  { label: 'primarily', bold: true, explain: '主要地' },
  { label: 'mainly', bold: false, explain: '主要地' },
  { label: 'chiefly', bold: true, explain: '首席地' },
  { label: 'proceed', bold: false, explain: '进行，继续' },
  { label: 'conduct', bold: false, explain: '进行，执行，指导' },
  { label: 'produce', bold: false, explain: '生产，制造' },
  { label: 'turn out', bold: true, explain: '结果是、证明是' },
  { label: 'profound', bold: false, explain: '深远的，深奧的' },
  { label: 'penetrating', bold: false, explain: '敏锐的，洞察的' },
  { label: 'prohibit', bold: true, explain: '禁止，阻止' },
  { label: 'ban', bold: true, explain: '禁令，禁止' },
  { label: 'forbid', bold: true, explain: '禁止，不允许' },
  { label: 'get rid of', bold: true, explain: '废除，摆脱' },
  { label: 'shake off', bold: true, explain: '摆脱，甩开' },
  { label: 'proper', bold: true, explain: '适当的' },
  { label: 'suitable', bold: true, explain: '合适的' },
  { label: 'appropriate', bold: true, explain: '恰当的' },
  { label: 'proposal', bold: true, explain: '提案、建议' },
  { label: 'proposition', bold: true, explain: '命题，提议' },
  { label: 'pursue by', bold: true, explain: '追求，寻找' },
  { label: 'go after', bold: false, explain: '追赶，寻找' },
  { label: 'track down', bold: false, explain: '追踪' },
  { label: 'put down', bold: false, explain: '放下，放置' },
  { label: 'deposit', bold: true, explain: '存放，存款' },
  { label: 'put up with', bold: false, explain: '忍受' },
  { label: 'tolerate', bold: true, explain: '容忍，忍受' },
  { label: 'endure', bold: true, explain: '忍受，忍耐' },
  { label: 'fed up with', bold: true, explain: '受够了，厌倦' },
  { label: 'sick of', bold: true, explain: '厌烦了' },
  { label: 'bear', bold: false, explain: '忍受' },
  { label: 'realistic', bold: true, explain: '现实的，实际的' },
  { label: 'reality', bold: false, explain: '现实，实际' },
  { label: 'practical', bold: true, explain: '实际的，实用的' },
  { label: 'actual', bold: false, explain: '现实的，真实的' },
  { label: 'reasonable', bold: true, explain: '合理的' },
  { label: 'sensible', bold: true, explain: '明智的' },
  { label: 'rational', bold: true, explain: '理性的' },
  { label: 'recognize', bold: false, explain: '认出，识别' },
  { label: 'recognition', bold: true, explain: '认出' },
  { label: 'admit to', bold: false, explain: '承认，供认' },
  { label: 'radical', bold: true, explain: '激进的，彻底的' },
  { label: 'fierce', bold: true, explain: '激烈的，猛烈的' },
  { label: 'drastic', bold: true, explain: '激烈的，严重的' },
  { label: 'intense', bold: true, explain: '强烈的，紧张的' },
  { label: 'redundant', bold: true, explain: '多余的，过剩的' },
  { label: 'excess', bold: false, explain: '超出的' },
  { label: 'extra', bold: true, explain: '额外的' },
  { label: 'refined', bold: true, explain: '高雅的，精致的' },
  { label: 'elegant', bold: true, explain: '优雅的' },
  { label: 'graceful', bold: false, explain: '优美的' },
  { label: 'reflect', bold: false, explain: '反应，表现' },
  { label: 'reflect on', bold: true, explain: '反思，思考' },
  { label: 'ponder', bold: true, explain: '沉思，思考' },
  { label: 'refuse', bold: true, explain: '拒绝' },
  { label: 'deny', bold: true, explain: '否定' },
  { label: 'reject', bold: true, explain: '拒绝' },
  { label: 'turn down', bold: true, explain: '拒绝' },
  { label: 'regular', bold: false, explain: '常规的，规律的'},
  { label: 'routine', bold: false, explain: '例行的' },
  { label: 'relevant', bold: false, explain: '相关的' },
  { label: 'associate with', bold: false, explain: '与…有关联' },
  { label: 'relate', bold: false, explain: '联系'},
  { label: 'reliable', bold: false, explain: '可靠的'},
  { label: 'dependable', bold: true, explain: '可信赖的'},
  { label: 'credible', bold: true, explain: '可信的'},
  { label: 'remark', bold: true, explain: '演讲，言论' },
  { label: 'speech', bold: false, explain: '演讲'},
  { label: 'opinion', bold: true, explain: '观点'},
  { label: 'resist', bold: false, explain: '抵抗' },
  { label: 'oppose', bold: true, explain: '反对'},
  { label: 'stand up to', bold: false, explain: '对抗'},
  { label: 'resort', bold: true, explain: '依赖，求助于' },
  { label: 'rely on', bold: true, explain: '依赖' },
  { label: 'depend on', bold: true, explain: '依赖' },
  { label: 'responsive', bold: true, explain: '反应敏捷的'},
  { label: 'sensitive', bold: true, explain: '敏感的' },
  { label: 'delicate', bold: true, explain: '精致的' },
  { label: 'result', bold: false, explain: '' },
  { label: 'consequence', bold: true, explain: '后果' },
  { label: 'revive', bold: true, explain: '复苏' },
  { label: 'survive', bold: true, explain: '生存' },
  { label: 'rigorous', bold: true, explain: '严格的' },
  { label: 'strict', bold: true, explain: '' },
  { label: 'rival', bold: true, explain: '竞争对手' },
  { label: 'opponent', bold: true, explain: '对手' },
  { label: 'enemy', bold: false, explain: '敌人' },
  { label: 'rotten', bold: false, explain: '腐烂的' },
  { label: 'corrupt', bold: false, explain: '腐败的' },
  // { label: 'rough', bold: true, explain: '粗略的' },
  // { label: 'approximate', bold: true, explain: '大概、大约' },
  // { label: 'ruin', bold: false, explain: '毁坏' },
  // { label: 'bankruptcy', bold: true, explain: '破产' },
  // { label: 'go broke', bold: false, explain: '破产' },
  // { label: 'crash', bold: true, explain: '崩溃' },
  // { label: 'salvation', bold: true, explain: '拯救' },
  // { label: 'rescue', bold: true, explain: '营救' },
  // { label: 'saturate', bold: false, explain: '浸湿，湿透' },
  // { label: 'drench', bold: true, explain: '湿透' },
  // { label: 'scrutiny', bold: true, explain: '审查' },
  // { label: 'examination', bold: false, explain: '检查' },
  // { label: 'satisfy', bold: false, explain: '满足' },
  // { label: 'fulfill', bold: true, explain: '履行' },
  // { label: 'seem to', bold: true, explain: '看上去，外观上' },
  // { label: 'superficial', bold: true, explain: '表面的' },
  // { label: 'sheer', bold: false, explain: '纯粹的' },
  // { label: 'pure', bold: false, explain: '纯净的' },
  // { label: 'situation', bold: true, explain: '情况' },
  // { label: 'condition', bold: true, explain: '条件' },
  // { label: 'specialty', bold: false, explain: '专业，专长' },
  // { label: 'fields', bold: false, explain: '领域' },
  // { label: 'speculate', bold: true, explain: '推测' },
  // { label: 'consider', bold: false, explain: '考虑' },
  // { label: 'spoil', bold: false, explain: '溺爱，宠坏' },
  // { label: 'indulge', bold: true, explain: '纵容' },
  // { label: 'spontaneous', bold: true, explain: '自发的' },
  // { label: 'automatic', bold: false, explain: '' },
  // { label: 'steady', bold: true, explain: '' },
  // { label: 'stable', bold: true, explain: '' },
  // { label: 'static', bold: true, explain: '静止的，静态的' },
  // { label: 'striking', bold: true, explain: '引人注目' },
  // { label: 'remarkable', bold: true, explain: '卓越的' }
]
export default vocabularyArray5
