import {Vocabulary} from "@/types/types.ts";

const vocabularyArray5: Vocabulary[] = [
  { label: "variety", bold: true, explain: "n. 种类,品种;多样性" },
  { label: "category", bold: false, explain: "n. 类别;种类" },
  { label: "sort", bold: false, explain: "n. 分类;排序;种类" },
  { label: "kind", bold: false, explain: "n. 种类" },
  { label: "species", bold: false, explain: "n. 物种" },
  { label: "territory", bold: true, explain: "n. 领域,领土,范围" },
  { label: "sphere", bold: false, explain: "n. 范围;领域" },
  { label: "field", bold: false, explain: "n. 领域" },
  { label: "domain", bold: false, explain: "n. 领域,范围" },
  { label: "district", bold: false, explain: "n. 地区;区域" },
  { label: "area", bold: false, explain: "n. 地区;地域" },
  { label: "realm", bold: false, explain: "n. 领域" },
  { label: "region", bold: false, explain: "n. 区域;地区" },
  { label: "zone", bold: false, explain: "n. 区域;分区" },
  { label: "migrate", bold: true, explain: "vi. 移动;移植;迁徙 vi. 使移居" },
  { label: "transfer", bold: false, explain: "v. 转移;搬迁" },
  { label: "relocate", bold: false, explain: "v. 搬迁,迁移" },
  { label: "resettle", bold: false, explain: "v. 重新定居;搬迁" },
  { label: "move", bold: false, explain: "v. 移动;改变位置;变化" },
  { label: "nourish", bold: true, explain: "vt. 养育,提供养分" },
  { label: "feed", bold: false, explain: "v. 养;饲养;进食" },
  { label: "cultivate", bold: false, explain: "vt. 培养;培育" },
  { label: "breed", bold: false, explain: "v. 生殖;饲养" },
  { label: "bring up", bold: false, explain: "养育;抚养;养" },
  { label: "exploit", bold: true, explain: "vt. 使用;开采" },
  { label: "use", bold: false, explain: "v. 使用;利用" },
  { label: "utilize", bold: false, explain: "vt. 使用;利用" },
  { label: "make use of", bold: false, explain: "使用;利用" },
  { label: "take advantage of", bold: false, explain: "利用" },
  { label: "decay", bold: true, explain: "vi. 腐烂,衰败 n. 腐烂" },
  { label: "rot", bold: false, explain: "v. 腐烂; (使)腐败变质" },
  { label: "spoil", bold: false, explain: "v. (食物)变质,腐败" },
  { label: "collapse", bold: true, explain: "vi./n. 倒塌" },
  { label: "fall", bold: false, explain: "v. 倒下,倒塌" },
  { label: "crumble", bold: false, explain: "v. 崩塌,坍塌" },
  { label: "fall down", bold: false, explain: "倒塌;跌倒" },
  { label: "impair", bold: true, explain: "vt. 损害,削弱" },
  { label: "damage", bold: false, explain: "vt. 损害;伤害;毁坏" },
  { label: "harm", bold: false, explain: "vt. 伤害;损害" },
  { label: "hurt", bold: false, explain: "v. 伤害; (使)疼痛,受伤" },
  { label: "erupt", bold: true, explain: "v. 爆发;喷发" },
  { label: "break out", bold: false, explain: "爆发" },
  { label: "spout", bold: false, explain: "v. (使)喷出，(使)喷射" },
  { label: "saturate", bold: true, explain: "vt. 使充满，使饱和" },
  { label: "cram", bold: false, explain: "v. 塞满；挤满" },
  { label: "fill", bold: false, explain: "v. 填满；(使)充满" },
  { label: "stuff", bold: false, explain: "vt. 填满；装满；塞满" },
  { label: "fertile", bold: true, explain: "adj. 多产的；肥沃的，富饶的" },
  { label: "prolific", bold: false, explain: "adj. 富饶的" },
  { label: "fruitful", bold: false, explain: "adj. 产量多的" },
  { label: "productive", bold: false, explain: "adj. 多产的" },
  { label: "ample", bold: true, explain: "adj. 丰富的；充足的" },
  { label: "abundant", bold: false, explain: "adj. 大量的；充裕的" },
  { label: "plentiful", bold: false, explain: "adj. 大量的；众多的" },
  { label: "enough", bold: false, explain: "adv. 足够地；充分地" },
  { label: "adequate", bold: false, explain: "adj. 充足的" },
  { label: "sufficient", bold: false, explain: "adj. 足够的；充足的" },
  { label: "large", bold: false, explain: "adj. 大规模的；大量的" },
  { label: "affluent", bold: false, explain: "adj. 丰富的，富足的" },
  { label: "plenty", bold: false, explain: "adj. 大量的；充裕的" },
  { label: "extraordinary", bold: true, explain: "adj. 特别的，异乎寻常的" },
  { label: "distinctive", bold: false, explain: "adj. 独特的" },
  { label: "exceptional", bold: false, explain: "adj. 不寻常的" },
  { label: "special", bold: false, explain: "adj. 特有的；特殊的" },
  { label: "particular", bold: false, explain: "adj. 特别的" },
  { label: "unusual", bold: false, explain: "adj. 特别的" },
  { label: "uncommon", bold: false, explain: "adj. 不常有的" },
  { label: "universal", bold: true, explain: "adj. 普遍的; 通用的; 全世界的; 宇宙的" },
  { label: "common", bold: false, explain: "adj. 常见的, 通常的" },
  { label: "prevalent", bold: false, explain: "adj. 普遍存在的" },
  { label: "general", bold: false, explain: "adj. 全体的, 普遍的" },
  { label: "widespread", bold: false, explain: "adj. 普遍的" },
  { label: "splendid", bold: true, explain: "adj. 壮丽的, 辉煌的" },
  { label: "glorious", bold: false, explain: "adj. 壮丽的, 辉煌的" },
  { label: "grand", bold: false, explain: "adj. 壮丽的, 宏伟的" },
  { label: "magnificent", bold: false, explain: "adj. 壮丽的" },
  { label: "superb", bold: false, explain: "adj. 卓越的, 壮丽的" },
  { label: "pollute", bold: true, explain: "v. 污染, 弄脏" },
  { label: "contaminate", bold: false, explain: "v. 污染" },
  { label: "stain", bold: false, explain: "v. 污染, 弄脏" },
  { label: "dirty", bold: false, explain: "v. 弄脏" },
  { label: "texture", bold: true, explain: "n. 质地, 结构" },
  { label: "composition", bold: false, explain: "n. 构成" },
  { label: "framework", bold: false, explain: "n. 结构, 构架" },
  { label: "structure", bold: false, explain: "n. 结构, 构造" },
  { label: "configuration", bold: false, explain: "n. 构造" },
  { label: "fabric", bold: false, explain: "n. 构造, 结构" },
  { label: "spacious", bold: true, explain: "adj. 广阔的, 宽敞的" },
  { label: "extensive", bold: false, explain: "adj. 广阔的; 广泛的" },
  { label: "broad", bold: false, explain: "adj. 宽广的, 宽敞的" },
  { label: "vast", bold: false, explain: "adj. 广阔的, 巨大的" },
  { label: "wide", bold: false, explain: "adj. 广泛的; 广阔的" },
  { label: "horizon", bold: true, explain: "n. 眼界; 地平线" },
  { label: "outlook", bold: false, explain: "n. 眼界, 观点" },
  { label: "vision", bold: false, explain: "n. 视野, 幻想" },
  { label: "view", bold: false, explain: "n. 眼界, 观点" },
  { label: "harness", bold: true, explain: "v. 利用, 治理" },
  { label: "use", bold: false, explain: "v. 利用, 使用" },
  { label: "utilize", bold: false, explain: "v. 利用, 使用" },
  { label: "manage", bold: false, explain: "v. 使用, 运用" },
  { label: "exploit", bold: false, explain: "v. 利用, 剥削" },
  { label: "innovation", bold: true, explain: "n. 创新, 改革, 新事物, 新方法" },
  { label: "renovation", bold: false, explain: "n. 革新, 翻新" },
  { label: "reform", bold: false, explain: "n. 改革; 改进; 改良" }
]
vocabularyArray5.forEach(item => {
  item.bold = false
})
export default vocabularyArray5
