import {Vocabulary} from "@/types/types.ts";

const vocabularyArray4: Vocabulary[] = [
    { label: "combat with", bold: false, explain: "v. 与...战斗；反对" },
    { label: "combat", bold: true, explain: "n. 战斗，搏斗 vt. 与...战斗；反对" },
    { label: "battle", bold: false, explain: "n. 战斗，搏斗 v. 与...作战" },
    { label: "conflict", bold: false, explain: "n. 战斗 v. 冲突" },
    { label: "fight", bold: false, explain: "n. 搏斗；打架 v. 与...作斗争" },
    { label: "war", bold: false, explain: "n. 战争 vi. 进行战斗；作战" },
    { label: "opponent", bold: true, explain: "n. 对手，敌手" },
    { label: "rival", bold: false, explain: "n. 竞争对手" },
    { label: "competitor", bold: false, explain: "n. 竞争对手" },
    { label: "enemy", bold: false, explain: "n. 敌人；仇人" },
    { label: "civilian", bold: true, explain: "n. 平民，百姓 adj. 平民的，民间的" },
    { label: "people", bold: false, explain: "n. 人；人们；人民" },
    { label: "citizen", bold: false, explain: "n. 公民；市民；老百姓" },
    { label: "civil", bold: false, explain: "adj. 公民的；国民的；平民的" },
    { label: "folk", bold: false, explain: "n. 人们；家人" },
    { label: "chaos", bold: true, explain: "n. 混沌，混乱" },
    { label: "riot", bold: false, explain: "n.v. 骚乱，闹事" },
    { label: "disorder", bold: false, explain: "n. 混乱；紊乱" },
    { label: "turbulence", bold: false, explain: "n. 动荡；骚乱" },
    { label: "mess", bold: false, explain: "n. 混乱；杂乱；肮脏" },
    { label: "oppose", bold: true, explain: "vt. 反对；抵制" },
    { label: "refuse", bold: false, explain: "v. 拒绝；回绝" },
    { label: "disagree", bold: false, explain: "v. 反对；不同意" },
    { label: "object", bold: false, explain: "v. 反对；不同意" },
    { label: "disapprove", bold: false, explain: "v. 反对；不同意" },
    // 弱爆
    { label: "rebel", bold: true, explain: "vi. 反抗，起义 n. 叛逆者，起义者" },
    // 若我逃
    { label: "revolt", bold: true, explain: "v. 反抗；起义；叛乱" },
    { label: "uprising", bold: false, explain: "n. 起义；造反" },
    // 手软的
    { label: "surrender", bold: true, explain: "vi. 投降；屈服，让步 vt. 交出，放弃" },
    { label: "submit", bold: false, explain: "vt. 屈服；提交；呈递" },
    { label: "yield", bold: false, explain: "vi. 屈服；放弃；产生" },
    { label: "capitulate", bold: false, explain: "vi. 屈服；屈从" },
    { label: "give up", bold: false, explain: "放弃；认输" },
    // 看弹幕
    { label: "condemn", bold: true, explain: "vt. 谴责；指责；宣判，判刑" },
    { label: "blame", bold: false, explain: "vt. 责备；责怪；指责" },
    // 阿Q死
    { label: "accuse", bold: false, explain: "vt. 指责，谴责；控告" },
    { label: "find fault with", bold: false, explain: "挑剔；找茬儿；指责" },
    // 弟闹事
    { label: "denounce", bold: false, explain: "vt. 谴责；指责" },
    { label: "criticize", bold: false, explain: "v. 批评；批判；挑剔" },
    { label: "appeal", bold: true, explain: "vi./n. 恳求,请求;呼吁" },
    { label: "plead", bold: false, explain: "v. 申辩;恳求;乞求" },
    { label: "implore", bold: false, explain: "v. 恳求;哀求" },
    { label: "pray", bold: false, explain: "v. 恳求;祈祷" },
    { label: "request", bold: false, explain: "n.vt. 请求,要求" },
    { label: "conquer", bold: true, explain: "vt. 战胜,征服" },
    { label: "win", bold: false, explain: "v. 赢;获胜" },
    { label: "defeat", bold: false, explain: "vt. 战胜;击败" },
    { label: "overcome", bold: false, explain: "vt. 克服;战胜" },
    { label: "triumph", bold: false, explain: "vi. 成功;战胜;报复" },
    { label: "dominate", bold: true, explain: "vt. 控制,统治,支配" },
    { label: "govern", bold: false, explain: "v. 控制;统治;管理" },
    { label: "control", bold: false, explain: "vt. 控制;指挥;尊重" },
    { label: "rule", bold: false, explain: "v. 控制;统治;支配" },
    { label: "reign", bold: false, explain: "vi. 统治;当政;为王" },
    { label: "administrate", bold: false, explain: "v. 管理,支配" },
    { label: "curb", bold: false, explain: "v. 控制,抑制" },
    { label: "damage", bold: true, explain: "vt. 损害,毁坏 n. 损害" },
    { label: "destroy", bold: false, explain: "vt. 摧毁;毁灭;破坏" },
    { label: "ruin", bold: false, explain: "vt. 破坏;毁灭;毁坏" },
    { label: "break", bold: false, explain: "v. 打破;(使)破,裂,碎" },
    { label: "destruct", bold: false, explain: "adj. 破坏的 vi. 破坏" },
    { label: "shatter", bold: false, explain: "v. 摧毁,粉碎" },
    { label: "aggressive", bold: false, explain: "adj. 好斗的,进攻的" },
    // 米粒弹他
    { label: "militant", bold: true, explain: "adj. 激进的；好斗的" },
    { label: "attacking", bold: true, explain: "adj. 攻击性的" },
    { label: "disclose", bold: true, explain: "v. 揭露，透露" },
    { label: "reveal", bold: true, explain: "vt. 揭露，展现；告诉" },
    { label: "expose", bold: true, explain: "vt. 揭露，暴露" },
    { label: "uncover", bold: true, explain: "vt. 揭露；发现" },
    { label: "give out", bold: true, explain: "公开，宣布" },
    { label: "confidential", bold: true, explain: "adj. 秘密的" },
    { label: "secret", bold: true, explain: "adj. 秘密的 n. 秘密；秘诀" },
    { label: "underground", bold: true, explain: "adj. 秘密的" },
    { label: "private", bold: true, explain: "adj. 私下的；秘密的" },
    { label: "backdoor", bold: true, explain: "adj. 秘密的" },
    { label: "recipe", bold: true, explain: "n. 食谱；秘诀；秘方" },
    { label: "law", bold: true, explain: "n. 法律，法规；规律，法则，定律" },
    // 弟cry
    { label: "decree", bold: true, explain: "n. 法令；政令" },
    { label: "code", bold: true, explain: "n. 法典，法规，章程；密码" },
    { label: "regulation", bold: true, explain: "n. 规章制度" },
    // 可迷信
    { label: "commission", bold: true, explain: "n. 委员会" },
    { label: "board", bold: false, explain: "n. 委员会, 理事会" },
    // 看守
    { label: "council", bold: false, explain: "n. 委员会" },
    { label: "delegation", bold: false, explain: "n. 代表团; 委托" },
    { label: "committee", bold: false, explain: "n. 委员会" },
    { label: "department", bold: true, explain: "n. 部, 司, 局, 处, 系" },
    { label: "ministry", bold: false, explain: "n. 部" },
    // 地位升
    { label: "division", bold: false, explain: "n. 部门; 级; 师" },
    { label: "bureau", bold: false, explain: "n. 办事处; 处; 科" },
    { label: "sector", bold: false, explain: "n. 部门, 领域; 行业" },
    { label: "perform", bold: true, explain: "vt. 施行, 完成" },
    { label: "fulfil", bold: false, explain: "v. 履行, 执行" },
    // 因破了门
    { label: "implement", bold: false, explain: "vt. 实施, 贯彻" },
    { label: "execute", bold: false, explain: "vt. 实行; 实施" },
    { label: "conduct", bold: false, explain: "v. 实施; 执行" },
    { label: "carry out", bold: false, explain: "实施; 执行; 实行" },
    { label: "inquiry", bold: true, explain: "n. 调查; 质询" },
    // 投资给谁？
    { label: "investigation", bold: false, explain: "n. 调查; 研究" },
    { label: "survey", bold: false, explain: "n. 调查" },
    { label: "research", bold: false, explain: "n.vt. 研究; 调查" },
    { label: "inspect", bold: false, explain: "vt. 检查; 查看" },
    { label: "examine", bold: false, explain: "vt. 检查; 考察" },
    { label: "illegal", bold: true, explain: "adj. 非法的, 不合法的" },
    { label: 'illicit', bold: false, explain: "非法的；违法的" },
    // 来接他们
    { label: "legitimate", bold: true, explain: "adj. 合法的；合理的" },
    { label: "legal", bold: false, explain: "adj. 合法的；法律的" },
    { label: "lawful", bold: false, explain: "adj. 法定的；法律承认的" },
    { label: "valid", bold: false, explain: "adj. 合法有效的；认可的" },
    { label: "rightful", bold: false, explain: "adj. 合法的；公正的" },
    { label: "deceive", bold: true, explain: "vt. 欺骗，蒙蔽" },
    { label: "cheat", bold: false, explain: "v. 欺骗；蒙骗" },
    { label: "lie", bold: false, explain: "v. 说谎；撒谎" },
    { label: "trick", bold: false, explain: "vt. 欺骗；欺诈" },
    { label: "fraud", bold: false, explain: "n. 欺诈；欺诈罪；骗子" },
    { label: "standard", bold: true, explain: "n. 标准；准则；准据" },
    { label: "criterion", bold: false, explain: "n. 标准；准则" },
    { label: "rule", bold: false, explain: "n. 规则；准则；条例" },
    { label: "guideline", bold: false, explain: "n. 准则；指南" },
    { label: "norm", bold: false, explain: "n. 标准；准则" },
    { label: "innocent", bold: true, explain: "adj. 无罪的，清白的；天真的" },
    { label: "blameless", bold: false, explain: "adj. 无过错的" },
    { label: "faultless", bold: false, explain: "adj. 没有错误的" },
    { label: "guiltless", bold: false, explain: "adj. 无辜的；无罪的" },
    { label: "sinless", bold: false, explain: "adj. 无罪；无罪的" },
    { label: "conform", bold: false, explain: "vi. 遵从,与……一致" },
    { label: "obey", bold: false, explain: "v. 服从;遵守;遵循" },
    { label: "observe", bold: false, explain: "v. 遵守;奉行" },
    { label: "comply", bold: false, explain: "vi. 遵守;遵从;服从" },
    { label: "abide by", bold: false, explain: "遵守;接受" },
    // 爱的我cat
    { label: "advocate", bold: true, explain: "vi. 提倡,主张,拥护 n. 拥护者" },
    { label: "support", bold: false, explain: "vt. 拥护;支持;鼓励" },
    { label: "appeal", bold: false, explain: "v. 呼吁" },
    { label: "call for", bold: false, explain: "需要;呼吁" },
    // 抗瘟神
    { label: "convention", bold: true, explain: "n. 惯例,习俗,公约" },
    // 路停!
    { label: "routine", bold: false, explain: "n. 常规;正常顺序" },
    { label: "custom", bold: false, explain: "n. 惯例;习惯;风俗" },
    { label: "forbid", bold: true, explain: "vt. 禁止,不准,不许" },
    { label: "ban", bold: false, explain: "vt. 禁止,取缔 n. 禁令" },
    // 破 + hibit
    { label: "prohibit", bold: false, explain: "vt. 禁止;阻止" },
    // 三个神
    { label: "sanction", bold: true, explain: "vt. 批准,认可 n. 批准,同意;制裁" },
    { label: "permit", bold: false, explain: "v. 批准" },
    { label: "allow", bold: false, explain: "v. 准许;允许" },
    { label: "approve", bold: false, explain: "v. 批准；赞成；同意" },
    { label: "license", bold: false, explain: "v. 许可；特许" },
    { label: "authorize", bold: false, explain: "vt. 批准；授权" },
    { label: "entitle", bold: true, explain: "vt. 授予...资格，给...称号" },
    { label: "empower", bold: false, explain: "vt. 授权" },
    { label: "grant", bold: false, explain: "v. 授予，给予" },
    { label: "confer", bold: false, explain: "v. 授予（奖项、学位）" },
    { label: "award", bold: false, explain: "v. 授予，颁发" },
    { label: "threaten", bold: true, explain: "vt. 威胁，恐吓" },
    { label: "intimidate", bold: false, explain: "vt. 恐吓，威胁" },
    { label: "terrorize", bold: false, explain: "vt. 威胁；恐吓" },
    { label: "menace", bold: false, explain: "v./n. 威胁，威吓" },
    { label: "frighten", bold: false, explain: "v. 吓唬；使惊吓" },
    // 霸凌
    { label: "bully", bold: false, explain: "vt. 恐吓；伤害；胁迫" },
    // 揣着
    { label: "treasure", bold: true, explain: "n. 财富；珍宝 vt. 珍视" },
    { label: "fortune", bold: false, explain: "n. 财富" },
    { label: "property", bold: false, explain: "n. 财产；财物" },
    { label: "asset", bold: false, explain: "n. 财产；资产" },
    { label: "wealth", bold: false, explain: "n. 财物；财富；富有" },
    { label: "money", bold: false, explain: "n. 财富；钱" },
    { label: "belongings", bold: false, explain: "n. 财物" },
    // 怕死不让死
    { label: "prosperous", bold: true, explain: "adj. 繁荣的，兴旺的" },
    { label: "affluent", bold: false, explain: "adj. 富裕的" },
    { label: "flourish", bold: false, explain: "v. 繁荣；昌盛" },
    { label: "boom", bold: false, explain: "v./n. 繁荣" },
    { label: "well-off", bold: false, explain: "adj. 富裕的" },
    { label: "wealthy", bold: false, explain: "adj. 富有的；富裕的" },
    { label: "rich", bold: false, explain: "adj. 富有的；富饶的" },
    // 是来福
    { label: "thrive", bold: false, explain: "vi. 兴旺发达；繁荣" },
    { label: "assess", bold: true, explain: "vt. 评估，估价" },
    { label: "appraise", bold: false, explain: "vt. 评价；估价；估量" },
    // 一万六 + it
    { label: "evaluate", bold: false, explain: "vt. 评估；评价" },
    { label: "salary", bold: true, explain: "n. 薪金，薪水" },
    { label: "pay", bold: false, explain: "n. 工资，薪 v. 支付，付" },
    // earn
    { label: "earnings", bold: false, explain: "n. 工资，薪" },
    { label: "wage", bold: false, explain: "n. 工资，报酬" },
    { label: "reward", bold: false, explain: "n. 奖励；回报；报酬" },
    { label: "accumulate", bold: true, explain: "v. 积累，积攒" },
    { label: "collect", bold: false, explain: "v. 收集；采集；收藏" },
    { label: "pile up", bold: false, explain: "堆积，积累" },
    { label: "gather", bold: false, explain: "v. 聚集；集合；召集" },
    { label: "consume", bold: true, explain: "vt. 消耗，消费" },
    { label: "expend", bold: false, explain: "vt. 支出；花费；消费" },
    { label: "waste", bold: false, explain: "v. 消耗；利用；运用" },
    { label: "spend", bold: false, explain: "v. 消耗；利用；运用" },
    { label: "use up", bold: false, explain: "消耗；耗尽" },
    { label: "slash", bold: false, explain: "v. 削减；砍" },
    { label: "cut", bold: false, explain: "n./v. 切；缩减" },
    { label: "decrease", bold: false, explain: "v. 减少，减小" },
    { label: "diminish", bold: false, explain: "vt. 减少，减小" },
    { label: "lessen", bold: false, explain: "v. (使)缩小，(使)减少" },
    { label: "deficient", bold: true, explain: "adj. 缺乏的，不足的" },
    { label: "lacking", bold: false, explain: "adj. 缺乏的" },
    { label: "insufficient", bold: false, explain: "adj. 不充分的" },
    { label: "short", bold: false, explain: "adj. 短缺的" },
    { label: "inadequate", bold: false, explain: "adj. 不充分的" },
    { label: "explain", bold: true, explain: "vt. 解释，说明" },
    // 因他怕
    { label: "interpret", bold: false, explain: "v. 解释，说明" },
    { label: "put across", bold: false, explain: "描述清楚；解释明白" },
    { label: "account for", bold: false, explain: "解释；占据" },
    // 地辐射
    { label: "diffuse", bold: true, explain: "v. 传播，扩散" },
    { label: "disperse", bold: false, explain: "v. 分散，散布" },
    { label: "transmit", bold: false, explain: "v. 传播；传导" },
    { label: "spread", bold: false, explain: "v. 传播；展开；摊开" },
    { label: "disseminate", bold: false, explain: "v. 传播；散布" },
    { label: "nurture", bold: true, explain: "v. 培育, 养育" },
    { label: "train", bold: false, explain: "v. 培训, 训练" },
    // 服侍他
    { label: "foster", bold: false, explain: "v. 培养, 抚育" },
    { label: "cultivate", bold: false, explain: "v. 培养, 种植" },
    { label: "educate", bold: false, explain: "v. 培养, 教育, 训练" },
    { label: "lead", bold: true, explain: "v. 引导, 指导" },
    { label: "guide", bold: false, explain: "v. 指导, 引导" },
    // 鹰死抓
    { label: "instruct", bold: false, explain: "v. 教导, 指导" },
    { label: "coach", bold: false, explain: "v. 训练, 辅导" },
    { label: "notify", bold: true, explain: "v. 通知, 报告" },
    { label: "inform", bold: false, explain: "v. 通知, 通告" },
    { label: "report", bold: false, explain: "v. 汇报, 报告" },
    { label: "approach", bold: true, explain: "n. 方法, 途径" },
    { label: "method", bold: false, explain: "n. 方法, 办法, 措施" },
    { label: "way", bold: false, explain: "n. 方法, 手段, 途径" },
    { label: "means", bold: false, explain: "n. 方法, 手段" },
    { label: "insight", bold: true, explain: "n. 洞察, 见解" },
    // 应吐一身
    { label: "intuition", bold: false, explain: "n. 直觉" },
    { label: "perception", bold: false, explain: "n. 知觉, 认知" },
    { label: "digest", bold: true, explain: "v. 理解; 消化; 领会" },
    { label: "understand", bold: false, explain: "v. 理解; 领会" },
    // 陪媳妇
    { label: "perceive", bold: false, explain: "vt. 理解; 认为" },
    { label: "follow", bold: false, explain: "vt. 理解; 跟随; 听从" },
    { label: "comprehend", bold: false, explain: "v. 理解; 领会" },
    { label: "see", bold: false, explain: "v. 理解; 看见" },
    { label: "grasp", bold: false, explain: "vt. 理解; 领会; 抓住" },
    { label: "cue", bold: true, explain: "v./n. 暗示; 提示" },
    { label: "suggestion", bold: false, explain: "n. 暗示; 建议" },
    // 恨她
    { label: "hint", bold: false, explain: "v./n. 暗示; 提示" },
    { label: "implication", bold: false, explain: "n. 暗指" },
    // 瑞克体罚
    { label: "rectify", bold: true, explain: "vt. 改正" },
    { label: "correct", bold: false, explain: "v. 纠正; 改正" },
    { label: "amend", bold: false, explain: "vt. 修正; 修订" },
    { label: "skim", bold: true, explain: "vt. 浏览" },
    { label: "browse", bold: false, explain: "v. 浏览; 随便看看" },
    { label: "scan", bold: false, explain: "v. 浏览; 扫描" },
    { label: "look through", bold: false, explain: "短语. 浏览; 翻阅" },
    { label: "initial", bold: true, explain: "adj. 最初的" },
    { label: "original", bold: false, explain: "adj. 起初的；原来的" },
    { label: "primary", bold: false, explain: "adj. 最初的；主要的" },
    { label: "honest", bold: true, explain: "adj. 真诚的，诚实的，正直的" },
    { label: "genuine", bold: false, explain: "adj. 真诚的；真正的" },
    // 心细啊
    { label: "sincere", bold: false, explain: "adj. 真诚的；诚挚的" },
    { label: "truthful", bold: false, explain: "adj. 诚实的；真实的" },
    { label: "upright", bold: false, explain: "adj. 正直的，诚实的" },
    { label: "polite", bold: true, explain: "adj. 有礼貌的；有教养的" },
    { label: "well-mannered", bold: false, explain: "adj. 有礼貌的" },
    { label: "courteous", bold: false, explain: "adj. 有礼貌的" },
    // 哥来吗
    { label: "glamour", bold: true, explain: "n. 魅力；魔法 vt. 迷惑；使有魅力 " },
    // 差吗
    { label: "charm", bold: false, explain: "n. 魅力；魔力" },
    { label: "fascination", bold: false, explain: "n. 极大的吸引力" },
    { label: "liability", bold: true, explain: "n. 责任，义务" },
    { label: "responsibility", bold: false, explain: "n. 责任" },
    { label: "duty", bold: false, explain: "n. 责任，义务，职责" },
    { label: "obligation", bold: false, explain: "n. 责任，义务" }
]
vocabularyArray4.forEach(item => {
    item.bold = false
})
export default vocabularyArray4
