import {Vocabulary} from "@/types/types.ts";

const vocabulary6: Vocabulary[] = [
    { label: "argue", bold: false, explain: "vt. 争辩 vt. 辩论；说服" },
    { label: "debate", bold: false, explain: "v. 争论，讨论" },
    { label: "dispute", bold: false, explain: "v. 争论，辩论" },
    { label: "neutral", bold: true, explain: "adj. 中立的，中性的" },
    { label: "independent", bold: false, explain: "adj. 客观公正的" },
    { label: "unprejudiced", bold: false, explain: "adj. 公平的；无偏见的" },
    { label: "unbiased", bold: false, explain: "adj. 无偏见的" },
    { label: "impartial", bold: false, explain: "adj. 不偏不倚的" },
    { label: "about", bold: true, explain: "adv. 大约" },
    { label: "approximately", bold: false, explain: "adv. 大约" },
    { label: "around", bold: false, explain: "adv. 大约" },
    { label: "near", bold: false, explain: "adv. 大约 adj. 近的，接近的" },
    { label: "roughly", bold: false, explain: "adv. 粗略地，大致上" },
    { label: "calculate", bold: true, explain: "vt. 估计；推测；计算；预测；认为" },
    { label: "compute", bold: false, explain: "vt. 计算；估算" },
    { label: "estimate", bold: false, explain: "v. 估计；估算；估价" },
    { label: "reckon", bold: false, explain: "v. 估计；认为" },
    { label: "justify", bold: true, explain: "vt. 证明" },
    { label: "prove", bold: true, explain: "vt. 证明; 结果是" },
    { label: "testify", bold: false, explain: "v. 作证; 证明" },
    { label: "confirm", bold: false, explain: "v. 证实, 证明" },
    { label: "certify", bold: true, explain: "v. 证实, 证明" },
    { label: "verify", bold: false, explain: "vt. 验证; 核实" },
    { label: "demonstrate", bold: false, explain: "v. 证明, 证实" },
    { label: "surpass", bold: true, explain: "vt. 超越, 胜过, 优于" },
    { label: "exceed", bold: false, explain: "vt. 超过, 超越" },
    { label: "transcend", bold: false, explain: "vt. 超越, 胜过" },
    { label: "go beyond", bold: false, explain: "短语. 超越" },
    { label: "concede", bold: true, explain: "vt. 承认, 退让, 给予, 容许" },
    { label: "admit", bold: false, explain: "vt. 承认, 接纳" },
    { label: "recognize", bold: false, explain: "vt. 认出, 承认" },
    { label: "confess", bold: false, explain: "vt. 承认, 供认" },
    { label: "acknowledge", bold: false, explain: "vt. 承认" },
    { label: "assume", bold: true, explain: "vt. 假定, 假设, 设想, 承担" },
    { label: "pretend", bold: false, explain: "vt. 假装" },
    { label: "simulate", bold: false, explain: "vt. 假装, 冒充" },
    { label: "act", bold: false, explain: "vt. 扮演, 表演" },
    { label: "reckon", bold: true, explain: "vt. 认为, 估计" },
    { label: "deem", bold: false, explain: "v. 认为, 视为" },
    { label: "consider", bold: false, explain: "v. 认为, 考虑" },
    { label: "suppose", bold: false, explain: "v. 认为, 假设" },
    { label: "regard", bold: false, explain: "v. 认为, 看待" },
    { label: "exaggerate", bold: true, explain: "v. 夸大, 夸张" },
    { label: "magnify", bold: false, explain: "vt. 放大, 夸张" },
    { label: "overstate", bold: false, explain: "vt. 夸张" },
    { label: "comment", bold: true, explain: "n./v. 评论, 注释" },
    { label: "remark", bold: false, explain: "n./v. 评论, 话语" },
    { label: "opinion", bold: false, explain: "n. 意见, 看法" },
    { label: "criticism", bold: false, explain: "n. 批评, 评论" },
    { label: "judgment", bold: false, explain: "n. 判断, 意见" },
    { label: "proclaim", bold: true, explain: "vt. 宣布, 声明, 赞扬" },
    { label: "announce", bold: false, explain: "v. 宣布, 宣告" },
    { label: "declare", bold: false, explain: "v. 宣布, 声明" },
    { label: "pronounce", bold: false, explain: "v. 正式宣布" },
    { label: "publicize", bold: false, explain: "vt. 宣传, 公布" },
    { label: "alert", bold: true, explain: "adj. 警惕的, 机敏的" },
    { label: "wary", bold: false, explain: "adj. 谨慎的, 警惕的" },
    { label: "cautious", bold: false, explain: "adj. 谨慎的, 小心的" },
    { label: "watchful", bold: false, explain: "adj. 注意的, 警惕的" },
    { label: "trend", bold: true, explain: "n. 趋势, 倾向" },
    { label: "tendency", bold: true, explain: "n. 趋势; 趋向" },
    { label: "tide", bold: false, explain: "n. 潮流; 趋势" },
    { label: "current", bold: false, explain: "n. 潮流; 趋向" },
    { label: "direction", bold: false, explain: "n. 趋势; 发展方向" },
    { label: "induce", bold: true, explain: "vt. 引诱, 引起" },
    { label: "lure", bold: false, explain: "v. 引诱, 诱惑" },
    { label: "elicit", bold: false, explain: "vt. 引起, 引出" },
    { label: "evoke", bold: false, explain: "vt. 唤起, 引起" },
    { label: "tempt", bold: false, explain: "v. 引诱, 诱惑" },
    { label: "pledge", bold: true, explain: "n. 承诺, 誓言, 保证" },
    { label: "promise", bold: false, explain: "n. 承诺" },
    { label: "swear", bold: false, explain: "v. 起誓保证, 发誓, 保证" },
    { label: "scarcely", bold: true, explain: "adv. 几乎不, 勉强" },
    { label: "hardly", bold: false, explain: "adv. 几乎不, 简直不, 仅仅" },
    { label: "barely", bold: false, explain: "adv. 勉强, 几乎不" },
    { label: "nearly", bold: true, explain: "adv. 几乎, 差不多" },
    { label: "almost", bold: false, explain: "adv. 几乎, 差不多" },
    { label: "virtually", bold: false, explain: "adv. 事实上" },
    { label: "principal", bold: true, explain: "adj. 最重要的, 主要的" },
    { label: "annoy", bold: true, explain: "vt. 打扰, 骚扰" },
    { label: "trouble", bold: false, explain: "v. 打扰, 使烦恼 n. 麻烦" },
    { label: "bother", bold: false, explain: "v. 打扰, 使烦恼" },
    { label: "upset", bold: false, explain: "vt. 使心烦意乱, 使生气" },
    { label: "bug", bold: false, explain: "v. 打扰, 使烦恼" },
    { label: "fade", bold: true, explain: "vi. 消失; 褪色" },
    { label: "vanish", bold: false, explain: "vi. 消失" },
    { label: "disappear", bold: false, explain: "vi. 消失" },
    { label: "evaporate", bold: false, explain: "v. 消失, 消散" },
    { label: "wear off", bold: false, explain: "短语. 磨损; 逐渐消失" },
    { label: "call off", bold: true, explain: "短语. 取消" },
    { label: "cancel", bold: false, explain: "vt. 取消; 删去" },
    { label: "abandon", bold: false, explain: "v. 放弃, 中止" },
    { label: "consequence", bold: true, explain: "n. 后果; 重要性" },
    { label: "result", bold: false, explain: "n. 后果; 结果" },
    { label: "outcome", bold: false, explain: "n. 结果; 效果" },
    { label: "ending", bold: false, explain: "n. 结尾, 结局" },
    { label: "aftermath", bold: false, explain: "n. 后果, 创伤" },
    { label: "factor", bold: true, explain: "n. 因素, 要素" },
    { label: "component", bold: false, explain: "n. 组成部分" },
    { label: "element", bold: false, explain: "n. 要素; 基本部分" },
    { label: "ingredient", bold: false, explain: "n. 因素, 要素" },
    { label: "situation", bold: true, explain: "n. 情况, 处境, 形势" },
    { label: "context", bold: false, explain: "n. 背景, 环境, 语境" },
    { label: "circumstance", bold: false, explain: "n. 情况, 环境" },
    { label: "case", bold: false, explain: "n. 情况, 案例" },
    { label: "condition", bold: false, explain: "n. 情况, 状态, 条件" },
    { label: "climax", bold: true, explain: "n. 顶点, 高潮" },
    { label: "top", bold: false, explain: "n. 顶部, 顶端" },
    { label: "peak", bold: false, explain: "n. 顶峰, 最高点" },
    { label: "below", bold: true, explain: "prep. 在...之下" },
    { label: "under", bold: false, explain: "prep. 在...下面" },
    { label: "beneath", bold: false, explain: "prep. 在...下方" },
    { label: "underneath", bold: false, explain: "prep. 在...下面" },
    { label: "eventually", bold: true, explain: "adv. 最后, 终于" },
    { label: "finally", bold: false, explain: "adv. 最后, 终于" },
    { label: "ultimately", bold: false, explain: "adv. 最终, 最后" },
    { label: "lastly", bold: false, explain: "adv. 最后" },
    { label: "compulsory", bold: true, explain: "adj. 必须的, 义务的, 强制的" },
    { label: "instant", bold: true, explain: "adj. 立刻的; 迫切的" },
    { label: "immediate", bold: false, explain: "adj. 立刻的" },
    { label: "urgent", bold: false, explain: "adj. 紧急的; 迫切的" },
    { label: "right away", bold: false, explain: "短语. 立刻, 马上" },
    { label: "at once", bold: false, explain: "短语. 立刻, 马上" },
    { label: "interior", bold: true, explain: "adj. 内部的; 里面的" },
    { label: "internal", bold: false, explain: "adj. 内部的; 国内的" },
    { label: "inner", bold: false, explain: "adj. 内部的; 内心的" },
    { label: "inside", bold: false, explain: "n. 里面; 内部; 内侧" },
    { label: "exterior", bold: true, explain: "adj. 外部的; 表面的" },
    { label: "external", bold: false, explain: "adj. 外部的; 外面的" },
    { label: "outer", bold: false, explain: "adj. 外部的; 外表的" },
    { label: "outside", bold: false, explain: "adj. 外部的; 在外面的" },
    { label: "interval", bold: true, explain: "n. 间隔, 间歇" },
    { label: "break", bold: false, explain: "n. 休息, 间歇" },
    { label: "pause", bold: false, explain: "n. 停顿; 停顿的时间" }
]
export default vocabulary6
