import { Vocabulary } from "../types/types.ts";


const vocabularyArray2: Vocabulary[] = [
  { label: 'amuse', bold: false, explain: '娱乐;逗……乐' },
  { label: 'entertain', bold: false, explain: '使娱乐' },
  { label: 'pastime', bold: false, explain: '娱乐,消遣' },
  { label: 'relaxation', bold: false, explain: '娱乐活动' },
  { label: 'recreation', bold: false, explain: '娱乐,消遣' },
  { label: 'journey', bold: false, explain: '旅行' },
  { label: 'tour', bold: false, explain: '旅行;旅游;' },
  { label: 'trip', bold: false, explain: '旅行;旅游' },
  { label: 'outing', bold: false, explain: '短途旅行' },
  { label: 'excursion', bold: false, explain: '短途旅行' },
  { label: 'trip', bold: false, explain: '旅行;旅游' },
  { label: 'dwell', bold: false, explain: '居住;存在于' },
  { label: 'live', bold: false, explain: '居住;住' },
  { label: 'inhabit', bold: false, explain: '居住在;栖居于' },
  { label: 'settle', bold: false, explain: '定居' },
  { label: 'residence', bold: false, explain: '住宅,住处' },
  { label: 'habitation', bold: false, explain: '住宅,住处' },
  { label: 'place', bold: false, explain: '住宅,住处' },
  { label: 'dwelling', bold: false, explain: '住宅,住处' },
  { label: 'ornament', bold: false, explain: '装饰 vt.装饰,修饰' },
  { label: 'adornment', bold: false, explain: '装饰;装饰物' },
  { label: 'decoration', bold: false, explain: '装饰;装饰品' },
  { label: 'leisure', bold: false, explain: '空闲,闲暇' },
  { label: 'idleness', bold: false, explain: '空闲' },
  { label: 'participate', bold: false, explain: '参与,参加' },
  { label: 'attend', bold: false, explain: '参加;出席' },
  { label: 'partake', bold: false, explain: '参与;参加' },
  { label: 'take part in', bold: false, explain: '参加;参与' },
  { label: 'cozy', bold: false, explain: '惬意的,舒适的' },
  { label: 'comfortable', bold: false, explain: '使人舒服的' },
  { label: 'homey', bold: false, explain: '愉快舒适的' },
  { label: 'pleasant', bold: false, explain: '舒适的,令人愉快的' },
  { label: 'intimate', bold: false, explain: '密切的,亲密的' },
  { label: 'familiar', bold: false, explain: '密切的,亲密的' },
  { label: 'pleasant', bold: false, explain: '令人愉快的' },
  { label: 'cheerful', bold: false, explain: '快乐的,愉快的' },
  { label: 'pleased', bold: false, explain: '高兴的;喜欢的' },
  { label: 'enthusiasm', bold: false, explain: '热情,积极性' },
  { label: 'eagerness', bold: false, explain: '热忱;渴望;殷切' },
  { label: 'passion', bold: false, explain: '热情;激情' },
  { label: 'career', bold: false, explain: '职业,生涯;经历' },
  { label: 'profession', bold: false, explain: '职业;行业' },
  { label: 'occupation', bold: false, explain: '工作;职业' },
  { label: 'vocation', bold: false, explain: '职业' },
  { label: 'cause', bold: false, explain: '事业;奋斗目标' },
  { label: 'recruit', bold: false, explain: '招聘 n.新成员,新兵' },
  { label: 'conscript', bold: false, explain: '征召入伍' },
  { label: 'enlist', bold: false, explain: '征集;征募;从军' },
  { label: 'enroll', bold: false, explain: '使加入;登记' },
  { label: 'employ', bold: false, explain: '雇用' },
  { label: 'sign up', bold: false, explain: '雇用;签约' },
  { label: 'engage', bold: false, explain: '从事;占用;vi.从事于,参加' },
  { label: 'undertake', bold: false, explain: '承担;从事' },
  { label: 'take up', bold: false, explain: '开始从事' },
  { label: 'distribute', bold: false, explain: '分配,分发' },
  { label: 'allot', bold: false, explain: '配给;分派' },
  { label: 'assign', bold: false, explain: '分配(某物)' },
  { label: 'allocate', bold: false, explain: '分派,分配' },
  { label: 'dismiss', bold: false, explain: '解散,解雇' },
  { label: 'discharge', bold: false, explain: '解雇;释放' },
  { label: 'send away', bold: false, explain: '解雇,遣走;遣散' },
  { label: 'lay off', bold: false, explain: '辞退,解雇' },
  { label: 'kick out', bold: false, explain: '解雇;开除' },
  { label: 'consult', bold: false, explain: '讨论;请教,咨询;商量' },
  { label: 'discuss', bold: false, explain: '讨论;谈论' },
  { label: 'confer', bold: false, explain: '讨论,交换意见' },
  { label: 'talk over', bold: false, explain: '详细讨论;坦诚交谈' },
  { label: 'modify', bold: false, explain: '修改;修饰;更改' },
  { label: 'amend ', bold: false, explain: '修正;修订' },
  { label: 'adjust', bold: false, explain: '调整;调节' },
  { label: 'alter', bold: false, explain: '改变;更改' },
  { label: 'inspire', bold: false, explain: 'vt.激励，使产生灵感' },
  { label: 'encourage', bold: false, explain: 'vt.鼓励；激励' },
  { label: 'stimulate', bold: false, explain: 'vt.刺激；激励' },
  { label: 'cheer', bold: false, explain: 'v.鼓励；喝彩' },
  { label: 'support', bold: false, explain: 'vt.鼓励；支持；拥护' },
  { label: 'hit', bold: false, explain: 'v./n.打击；产生不良影响' },
  { label: 'knock', bold: false, explain: 'v.敲，击，打，无端指责' },
  { label: 'beat', bold: false, explain: 'v.击败，连续击打' },
  { label: 'frustration', bold: false, explain: 'n.挫折，挫败' },
  { label: 'setback', bold: false, explain: '挫折' },
  { label: 'failure', bold: false, explain: '失败' },
  { label: 'rivalry', bold: false, explain: 'n.竞争；对抗' },
  { label: 'competition', bold: false, explain: 'n.竞争，比赛' },
  { label: 'contest', bold: false, explain: 'n.竞赛，比赛' },
  { label: 'combine', bold: false, explain: 'v.联合，结合' },
  { label: 'unite', bold: false, explain: 'v.联合，团结；统一' },
  { label: 'bond', bold: false, explain: 'n.纽带；联系；关系' },
  { label: 'associate', bold: false, explain: 'v.联合；联想' },
  { label: 'couple', bold: false, explain: 'v.连接，结合' },
  { label: 'connect', bold: false, explain: 'v.连接；接通' },
  { label: 'merge', bold: false, explain: 'v.合并；融入；结合' },
  { label: 'incorporate', bold: false, explain: 'vt.合并；包含' },
  { label: 'integrate', bold: false, explain: 'v.整合；合并' },
  { label: 'create', bold: true, explain: 'vt.产生；创造，创作' },
  { label: 'produce', bold: false, explain: 'vt.生产；制造' },
  { label: 'generate', bold: false, explain: 'vt.生成；产生' },
  { label: 'arouse', bold: false, explain: 'vt.激起，引发' },
  { label: 'cause', bold: false, explain: 'vt.使发生；造成' },
  { label: 'vacant', bold: true, explain: 'adj.空的；空缺的' },
  { label: 'empty', bold: false, explain: 'adj.空的；空洞的' },
  { label: 'unoccupied', bold: false, explain: 'adj.空着的' },
  { label: 'blank', bold: false, explain: 'adj.空白的' },
  { label: 'hollow', bold: false, explain: 'adj.空洞的，空虚的' },
  { label: 'competent', bold: true, explain: 'adj.有能力的，胜任的' },
  { label: 'able', bold: false, explain: 'adj.能够的；有能力的' },
  { label: 'capable', bold: false, explain: 'adj.有能力的；有才能的' },
  { label: 'qualified', bold: false, explain: 'adj.胜任的；合格的' },
  { label: 'eligible', bold: false, explain: 'adj.有资格的；符合条件的' },
  { label: 'endeavor', bold: true, explain: 'n.努力；尽力 vi.努力；尽力' },
  { label: 'effort', bold: false, explain: 'n.努力' },
  { label: 'strive', bold: false, explain: 'vi.努力；奋斗' },
  { label: 'work hard', bold: false, explain: '努力工作' },
  { label: 'insist', bold: true, explain: 'vt.坚持' },
  { label: 'persevere', bold: false, explain: 'v.坚持' },
  { label: 'persist', bold: false, explain: 'vi.坚持' },
  { label: 'stick to', bold: false, explain: '坚持；粘附' },
  { label: 'cling to', bold: false, explain: '坚持' },
  { label: 'cause', bold: true, explain: 'n.原因；事业 vt.引起' },
  { label: 'reason', bold: false, explain: 'n.原因；理由' },
  { label: 'excuse', bold: false, explain: 'n.借口；辩解' },
  { label: 'healthy', bold: false, explain: '健康的;健壮的' },
  { label: 'sound', bold: false, explain: '健康的' },
  { label: 'sturdy', bold: true, explain: 'adj.强健的；坚固的；坚定的' },
  { label: 'robust', bold: false, explain: 'adj.强健的；强劲的' },
  { label: 'powerful', bold: false, explain: 'adj.强大的' },
  { label: 'firm', bold: false, explain: 'adj.坚固的；坚硬的' },
  { label: 'muscular', bold: false, explain: 'adj.强壮的' },
  { label: 'strong', bold: false, explain: 'adj.坚强的；强劲的' },
  { label: 'energetic', bold: false, explain: 'adj.精力充沛的' },
  { label: 'invalid', bold: true, explain: 'adj.病弱的；无效的 n.病人' },
  { label: 'weak', bold: false, explain: 'adj.虚弱的；无力的' },
  { label: 'feeble', bold: false, explain: 'adj.虚弱的；无力的' },
  { label: 'disabled', bold: false, explain: 'adj.有残疾的' },
  { label: 'sick', bold: false, explain: 'adj.有病的；患病的' },
  { label: 'unhealthy', bold: false, explain: 'adj.不健康的' },
  { label: 'ill', bold: false, explain: 'adj.有病的；恶意的' },
  { label: 'rescue', bold: true, explain: 'vt./n.救援，营救' },
  { label: 'aid', bold: false, explain: 'vi.救援，援助' },
  { label: 'save', bold: false, explain: 'v.救治；挽救' },
  { label: 'preserve', bold: false, explain: '保护,保存' },
  { label: 'conserve', bold: true, explain: 'vt.保存；保护' },
  { label: 'defend', bold: false, explain: 'v.防御；保护；保卫' },
  { label: 'guard', bold: false, explain: 'n.保护；警卫；保卫' },
  { label: 'protect', bold: false, explain: 'v.防护；保护' },
  { label: 'secure', bold: false, explain: 'vt.保护；获得' },
  { label: 'shield', bold: false, explain: 'n.保护人；保护物' },
  { label: 'shelter', bold: false, explain: 'v.提供庇护，提供保护' },
  { label: 'suffer', bold: true, explain: 'vi.忍受痛苦；受损失 vt.受苦，受罪' },
  { label: 'endure', bold: false, explain: 'v.忍耐；忍受' },
  { label: 'undergo', bold: false, explain: 'vt.遭受，经历' },
  { label: 'resist', bold: false, explain: 'v.耐得住；抵抗住' },
  { label: 'tolerate', bold: false, explain: 'vt.忍受；容忍；包容' },
  { label: 'stand', bold: false, explain: 'v.容忍，忍受' },
  { label: 'bear', bold: false, explain: 'v.承受；忍受' },
  { label: 'withstand', bold: false, explain: 'vt.抵挡，经受住' },
  { label: 'put up with', bold: false, explain: '忍受；容忍' },
  { label: 'tackle', bold: true, explain: 'vt.处理，解决' },
  { label: 'overcome', bold: false, explain: 'vt.解决；克服' },
  { label: 'solve', bold: false, explain: 'vt.解决；处理' },
  { label: 'handle', bold: false, explain: 'v.处理，应付' },
  { label: 'address', bold: false, explain: 'v.处理；演讲' },
  { label: 'deal with', bold: false, explain: '处理；应付' },
  { label: 'cope with', bold: false, explain: '处理；对待' },
  { label: 'forecast', bold: true, explain: 'v./n.预测；预报' },
  { label: 'predict', bold: false, explain: 'v.预测；预言' },
  { label: 'foresee', bold: false, explain: 'v.预料；预见；预知' },
  { label: 'expect', bold: false, explain: 'v.预计；预期' },
  { label: 'consolidate', bold: true, explain: 'vi.加强，巩固 vt.使巩固；联合' },
  { label: 'strengthen', bold: false, explain: 'v.加强；增强' },
  { label: 'reinforce', bold: false, explain: 'vt.加强；充实' },
  { label: 'intensify', bold: false, explain: 'v.强化；加强' },
  { label: 'enhance', bold: false, explain: 'vt.增强；增进' },
  { label: 'restore', bold: true, explain: 'vt.恢复；归还，放回' },
  { label: 'recover', bold: false, explain: 'v.恢复；复原' },
  { label: 'resume', bold: false, explain: 'v.恢复，回到' },
  { label: 'revive', bold: false, explain: 'v.恢复，复兴' },
  { label: 'wonder', bold: true, explain: 'n.奇迹；惊奇 v.诧异' },
  { label: 'marvel', bold: false, explain: 'n.令人惊异的人；奇迹' },
  { label: 'miracle', bold: false, explain: 'n.奇迹；圣迹；神迹' },
  { label: 'resign', bold: true, explain: 'vt.放弃；辞职 vi.辞职' },
  { label: 'abandon', bold: false, explain: 'vt.放弃；离弃' },
  { label: 'quit', bold: false, explain: 'v.退出；戒掉；停止' },
  { label: 'give up', bold: false, explain: '放弃；戒除；认输' }

]
export default vocabularyArray2
