import { Vocabulary } from "../types/types.ts";


const vocabularyArray2: Vocabulary[] = [
  { label: 'amuse', bold: false, explain: '娱乐;逗……乐' },
  { label: 'entertain', bold: false, explain: '使娱乐' },
  { label: 'pastime', bold: false, explain: '娱乐,消遣' },
  { label: 'relaxation', bold: false, explain: '娱乐活动' },
  { label: 'recreation', bold: false, explain: '娱乐,消遣' },
  { label: 'journey', bold: false, explain: '旅行' },
  { label: 'tour', bold: false, explain: '旅行;旅游;' },
  { label: 'trip', bold: false, explain: '旅行;旅游' },
  { label: 'outing', bold: false, explain: '短途旅行' },
  { label: 'excursion', bold: false, explain: '短途旅行' },
  { label: 'trip', bold: false, explain: '旅行;旅游' },
  { label: 'dwell', bold: false, explain: '居住;存在于' },
  { label: 'live', bold: false, explain: '居住;住' },
  { label: 'inhabit', bold: false, explain: '居住在;栖居于' },
  { label: 'settle', bold: false, explain: '定居' },
  { label: 'residence', bold: false, explain: '住宅,住处' },
  { label: 'habitation', bold: false, explain: '住宅,住处' },
  { label: 'place', bold: false, explain: '住宅,住处' },
  { label: 'dwelling', bold: false, explain: '住宅,住处' },
  { label: 'ornament', bold: false, explain: '装饰 vt.装饰,修饰' },
  { label: 'adornment', bold: false, explain: '装饰;装饰物' },
  { label: 'decoration', bold: false, explain: '装饰;装饰品' },
  { label: 'leisure', bold: false, explain: '空闲,闲暇' },
  { label: 'idleness', bold: false, explain: '空闲' },
  { label: 'participate', bold: false, explain: '参与,参加' },
  { label: 'attend', bold: false, explain: '参加;出席' },
  { label: 'partake', bold: false, explain: '参与;参加' },
  { label: 'take part in', bold: false, explain: '参加;参与' },
  { label: 'cozy', bold: false, explain: '惬意的,舒适的' },
  { label: 'comfortable', bold: false, explain: '使人舒服的' },
  { label: 'homey', bold: false, explain: '愉快舒适的' },
  { label: 'pleasant', bold: false, explain: '舒适的,令人愉快的' },
  { label: 'intimate', bold: false, explain: '密切的,亲密的' },
  { label: 'familiar', bold: false, explain: '密切的,亲密的' },
  { label: 'pleasant', bold: false, explain: '令人愉快的' },
  { label: 'cheerful', bold: false, explain: '快乐的,愉快的' },
  { label: 'pleased', bold: false, explain: '高兴的;喜欢的' },
  { label: 'enthusiasm', bold: false, explain: '热情,积极性' },
  { label: 'eagerness', bold: false, explain: '热忱;渴望;殷切' },
  { label: 'passion', bold: false, explain: '热情;激情' },
  { label: 'career', bold: false, explain: '职业,生涯;经历' },
  { label: 'profession', bold: false, explain: '职业;行业' },
  { label: 'occupation', bold: false, explain: '工作;职业' },
  { label: 'vocation', bold: false, explain: '职业' },
  { label: 'cause', bold: false, explain: '事业;奋斗目标' },
  { label: 'recruit', bold: false, explain: '招聘 n.新成员,新兵' },
  { label: 'conscript', bold: false, explain: '征召入伍' },
  { label: 'enlist', bold: false, explain: '征集;征募;从军' },
  { label: 'enroll', bold: false, explain: '使加入;登记' },
  { label: 'employ', bold: false, explain: '雇用' },
  { label: 'sign up', bold: false, explain: '雇用;签约' },
  { label: 'engage', bold: false, explain: '从事;占用;vi.从事于,参加' },
  { label: 'undertake', bold: false, explain: '承担;从事' },
  { label: 'take up', bold: false, explain: '开始从事' },
  { label: 'cause', bold: false, explain: '事业;奋斗目标' },
]
export default vocabularyArray2
