import { Vocabulary } from "../types/types.ts";


const vocabularyArray2: Vocabulary[] = [
  { label: 'be stuck with', bold: true, explain: '被困扰' },
  { label: 'cursed with', bold: true, explain: '被诅咒或困扰' },
  { label: 'confound', bold: false, explain: '使困惑' },
  { label: 'be well-known', bold: true, explain: '' },
  { label: 'famous', bold: true, explain: '' },
  { label: 'beams', bold: true, explain: '光束' },
  { label: 'rays', bold: false, explain: '' },
  { label: 'beneath', bold: false, explain: '下面，之下' },
  { label: 'below', bold: false, explain: '' },
  { label: 'underneath', bold: false, explain: '' },
  { label: 'beyond', bold: false, explain: '' },
  { label: 'transcend', bold: true, explain: '超越' },
  { label: 'surpass', bold: true, explain: '超越' },
  { label: 'exceed', bold: true, explain: '超过' },
  { label: 'bloom', bold: true, explain: '繁荣，绽放' },
  { label: 'blossom', bold: true, explain: '繁荣' },
  { label: 'brisk', bold: true, explain: '繁荣' },
  { label: 'flourish', bold: true, explain: '繁荣' },
  { label: 'prosperous', bold: true, explain: '经济繁荣' },
  { label: 'bring about', bold: true, explain: '引起、导致' },
  { label: 'bring up', bold: true, explain: '提出、教育、抚养' },
  { label: 'browse', bold: false, explain: '翻阅，浏览' },
  { label: 'leaf through', bold: true, explain: '翻阅' },
  { label: 'run over', bold: false, explain: '快速浏览' },
  { label: 'burden', bold: false, explain: '负担' },
  { label: 'budget', bold: false, explain: '预算' },
  { label: 'burned out', bold: false, explain: '疲惫不堪' },
  { label: 'exhausted', bold: true, explain: '筋疲力尽的' },
  { label: 'brutal', bold: true, explain: '残忍的' },
  { label: 'cruel', bold: false, explain: '残忍的' },
  { label: 'cannot be too', bold: true, explain: '再…也不为过' },
  { label: 'cannot help doing', bold: true, explain: '不由自主地' },
  { label: 'carefully', bold: false, explain: '' },
  { label: 'cautiously', bold: true, explain: '谨慎地，小心地' },
  { label: 'case of suspect', bold: true, explain: '被怀疑的地方' },
  { label: 'doubt', bold: false, explain: '怀疑的情况' },
  { label: 'cease', bold: true, explain: '' },
  { label: 'stop', bold: false, explain: '' },
  { label: 'halt', bold: false, explain: '' },
  { label: 'terminate', bold: true, explain: '停止、结束' },
  { label: 'channel', bold: false, explain: '' },
  { label: 'medium', bold: false, explain: '' },
  { label: 'chronic', bold: false, explain: '慢性的、长期的' },
  { label: 'continuous', bold: true, explain: '连续持续的' },
  { label: 'circulation', bold: true, explain: '发行' },
  { label: 'spreading', bold: false, explain: '传播' },
  { label: 'cited', bold: true, explain: '引用' },
  { label: 'mentioned', bold: true, explain: '提及' },
  { label: 'chilly', bold: false, explain: '' },
  { label: 'clause', bold: true, explain: '条款' },
  { label: 'legislative', bold: true, explain: '立法的' },
  { label: 'Provision', bold: true, explain: '规定' },
  { label: 'clues', bold: false, explain: '线索' },
  { label: 'hints', bold: false, explain: '提示' },
  { label: 'combat', bold: false, explain: '战斗' },
  { label: 'fight against', bold: true, explain: '' },
  { label: 'combination', bold: true, explain: '' },
  { label: 'integration', bold: true, explain: '整合' },
  { label: 'come out', bold: false, explain: '' },
  { label: 'be published', bold: false, explain: '' },
  { label: 'commitment', bold: true, explain: '承诺' },
  { label: 'undertake', bold: true, explain: '承担' },
  { label: 'compact', bold: false, explain: '' },
  { label: 'compress', bold: true, explain: '压缩' },
  { label: 'comparable', bold: true, explain: '' },
  { label: 'resemble', bold: true, explain: '' },
  { label: 'equal', bold: true, explain: '' },
  { label: 'take after', bold: true, explain: '' },
  { label: 'compatible with', bold: false, explain: '与…兼容' },
  { label: 'be consistent with', bold: false, explain: '与某事一致' },
  { label: 'compensation', bold: true, explain: '补偿' },
  { label: 'make up for', bold: true, explain: '弥补' },
  { label: 'subsidy', bold: false, explain: '补贴' },
  { label: 'competition', bold: true, explain: '竞争' },
  { label: 'rivalry', bold: true, explain: '竞争' },
  { label: 'complain to', bold: false, explain: '抱怨' },
  { label: 'sound off', bold: true, explain: '抱怨' },
  { label: 'comply with', bold: true, explain: '遵守' },
  { label: 'follow', bold: true, explain: '遵循' },
  { label: 'observe', bold: true, explain: '遵守' },
  { label: 'abide by', bold: true, explain: '遵守' },
  { label: 'compose', bold: false, explain: '构成' },
  { label: 'make up', bold: true, explain: '组成' },
  { label: 'comprehension', bold: false, explain: '理解' },
  { label: 'make sense of', bold: false, explain: '' },
  { label: 'compulsory', bold: false, explain: '强制的' },
  { label: 'required', bold: false, explain: '' },
  { label: 'obliged', bold: true, explain: '有义务的' },
  { label: 'conceive', bold: false, explain: '构思' },
  { label: 'formulate', bold: true, explain: '制定' },
  { label: 'confidence', bold: false, explain: '' },
  { label: 'optimism', bold: true, explain: '乐观' },
  { label: 'confined', bold: true, explain: '受限的' },
  { label: 'restricted', bold: true, explain: '受限的' },
  { label: 'confirm', bold: true, explain: '确认' },
  { label: 'affirm', bold: true, explain: '肯定' },
  { label: 'allege', bold: true, explain: '声称' },
  { label: 'congestion', bold: true, explain: '拥挤' },
  { label: 'crowd', bold: false, explain: '人群拥挤' },
  { label: 'intensive', bold: false, explain: '密集的' },
  { label: 'consensus', bold: true, explain: '共识' },
  { label: 'agreement', bold: false, explain: '' },
  { label: 'consider', bold: false, explain: '' },
  { label: 'allow for', bold: false, explain: '' },
  { label: 'considerably', bold: false, explain: '相当大地' },
  { label: 'plentifully', bold: false, explain: '充足地' },
  { label: 'substantially', bold: true, explain: '大幅度地' },
  { label: 'be consistent with', bold: false, explain: '与⋯一致' },
  { label: 'be compatible with', bold: true, explain: '与⋯兼容' },
  { label: 'consists in', bold: true, explain: ' 在于...' },
  { label: 'lie in', bold: true, explain: ' 在于...' },
  { label: 'constraint', bold: true, explain: '约束' },
  { label: 'restriction', bold: true, explain: '限制' },
  { label: 'consulting with', bold: true, explain: '与.商议' },
  { label: 'confer', bold: false, explain: '商议' },
  { label: 'discuss', bold: false, explain: '讨论' },
  { label: 'continuous', bold: false, explain: '连续的' },
  { label: 'successive', bold: true, explain: '连续的' },
  { label: 'uninterrupted', bold: false, explain: '不断地' },
  { label: 'contradiction', bold: true, explain: '矛盾' },
  { label: 'conflict', bold: true, explain: '冲突' },
  { label: 'interference', bold: true, explain: '干涉' },
  { label: 'contributing to', bold: false, explain: '有助于' },
  { label: 'devote to', bold: true, explain: '专注于' },
  { label: 'conventional', bold: false, explain: '传统的' },
  { label: 'traditional', bold: true, explain: '传统的' },
  { label: 'orthodox', bold: true, explain: '正统的' },
  { label: 'convert', bold: true, explain: '转变' },
  { label: 'turn', bold: false, explain: '转动' },
  { label: 'turn over', bold: false, explain: '翻转' },
]
export default vocabularyArray2
