import {Vocabulary} from "./types";

const vocabularyArray3: Vocabulary[] = [
    { label: 'convey', bold: false, explain: '传达'},
    { label: 'deliver', bold: true, explain: '交付，运输'},
    { label: 'transport', bold: false, explain: '运输'},
    { label: 'convicted', bold: true, explain: '被定罪的' },
    { label: 'condemned', bold: true, explain: '被严厉谴责的'},
    { label: 'count on', bold: false, explain: '依靠' },
    { label: 'lean on', bold: true, explain: '依靠' },
    { label: 'coordinate', bold: true, explain: '协调' },
    { label: 'regulate', bold: true, explain: '规范' },
    { label: 'create', bold: false, explain: '创造' },
    { label: 'produce', bold: false, explain: '生产' },
    { label: 'generate', bold: true, explain: '传达' },
    { label: 'invent', bold: false, explain: '发明' },
    { label: 'craft', bold: false, explain: '制作 ' },
    { label: 'criteria', bold: true, explain: '标准' },
    { label: 'standards', bold: false, explain: '标准' },
    { label: 'critical', bold: true, explain: '关键的' },
    { label: 'crucial', bold: true, explain: '关键的' },
    { label: 'criticize', bold: false, explain: '批评' },
    { label: 'find fault with', bold: false, explain: '挑剔' },
    { label: 'current', bold: false, explain: '' },
    { label: 'latest', bold: false, explain: '最新的' },
    { label: 'damp', bold: false, explain: '潮湿的' },
    { label: 'moist', bold: true, explain: '潮湿的' },
    { label: 'deadly', bold: false, explain: '致命的' },
    { label: 'fatal', bold: false, explain: '致命的' },
    { label: 'deception', bold: true, explain: '欺骗' },
    { label: 'cheating', bold: true, explain: '作弊' },
    { label: 'fraud', bold: true, explain: '欺诈'},
    { label: 'decisively', bold: true, explain: '果断地'},
    { label: 'resolutely', bold: true, explain: '坚决地'},
    { label: 'stand firm', bold: false, explain: '坚守，坚定'},
    { label: 'decorate', bold: false, explain: '装饰' },
    { label: 'beautify', bold: false, explain: '美化' },
    { label: 'decreased', bold: true, explain: '减少的' },
    { label: 'diminished', bold: false, explain: '下降的' },
    // { label: 'deduction', bold: false, explain: '推断' },
    // { label: 'inference', bold: false, explain: '推论' },
    // { label: 'reasoning', bold: false, explain: '推理' },
    // { label: 'defense', bold: false, explain: '' },
    // { label: 'protection', bold: false, explain: '' },
    // { label: 'deficiency', bold: false, explain: '' },
    // { label: 'deficit', bold: false, explain: '' },
    // { label: 'lack', bold: false, explain: '' },
    // { label: 'scarcity', bold: false, explain: '' },
    // { label: 'definitely', bold: false, explain: '' },
    // { label: 'necessarily', bold: false, explain: '' },
    // { label: 'specifically', bold: false, explain: '' },
    // { label: 'delay', bold: false, explain: '' },
    // { label: 'put off', bold: false, explain: '' },
    // { label: 'set back', bold: false, explain: '' },
    // { label: 'deliberate', bold: false, explain: '' },
    // { label: 'intentional', bold: false, explain: '' },
    // { label: 'on purpose', bold: false, explain: '' },
    // { label: 'purposeful', bold: false, explain: '' },
    // { label: 'delicate', bold: false, explain: '' },
    // { label: 'fine', bold: false, explain: '' },
    // { label: 'fragile', bold: false, explain: '' },
    // { label: 'tender', bold: false, explain: '' },
    // { label: 'demonstrated', bold: false, explain: '' },
    // { label: 'showed', bold: false, explain: '' },
    // { label: 'demonstrate', bold: false, explain: '' },
    // { label: 'manifest', bold: false, explain: '' },
    // { label: 'denied', bold: false, explain: '' },
    // { label: 'refused', bold: false, explain: '' },
    // { label: 'dense', bold: false, explain: '' },
    // { label: 'sparse', bold: false, explain: '' },
    // { label: 'thin', bold: false, explain: '' },
    // { label: 'depressed', bold: false, explain: '' },
    // { label: 'depression', bold: false, explain: '' },
    // { label: 'recession', bold: false, explain: '' },
    // { label: 'deserved', bold: false, explain: '' },
    // { label: 'due', bold: false, explain: '' },

]
export default vocabularyArray3
