import {Vocabulary} from "@/libs/types";

const vocabularyArray4: Vocabulary[] = [
    { label: 'fall down', bold: false, explain: '摔倒或跌落' },
    { label: 'collapse', bold: true, explain: '倒塌，塌下，崩溃' },
    { label: 'illusion', bold: true, explain: '幻觉，错觉，虚假的信仰' },
    { label: 'fasten', bold: true, explain: '系紧，扣紧，固定在' },
    { label: 'tied to', bold: true, explain: '与某事物或某人有紧密联系' },
    { label: 'faulty', bold: false, explain: '有缺陷的' },
    { label: 'imperfect', bold: true, explain: '不完美的' },
    { label: 'blunder', bold: false, explain: '大错' },
    { label: 'fantastic', bold: true, explain: '极好的，令人惊叹的' },
    { label: 'marvelous', bold: true, explain: '令人惊奇的' },
    { label: 'fear', bold: false, explain: '害怕，担忧' },
    { label: 'lest', bold: false, explain: '以免，唯恐' },
    { label: 'formidable', bold: true, explain: '可怕的、令人敬畏的' },
    { label: 'feature', bold: true, explain: '特质，特点' },
    { label: 'trait', bold: true, explain: '特质，特征' },
    { label: 'figure out', bold: true, explain: '理解，弄清楚' },
    { label: 'work out', bold: false, explain: '解决，制定' },
    { label: 'firm', bold: true, explain: '坚定的，坚决的,公司' },
    { label: 'resolute', bold: true, explain: '坚决的' },
    { label: 'fixed conception', bold: false, explain: '固执的观念' },
    { label: 'stereotype', bold: false, explain: '刻板印象、陈规' },
    { label: 'stubbornness', bold: true, explain: '固执、执拗' },
    { label: 'formation', bold: false, explain: '形成，组成' },
    { label: 'form', bold: false, explain: '形式，外表' },
    { label: 'fundamental', bold: true, explain: '基本的，根本的' },
    { label: 'underlying', bold: false, explain: '潜在的，基础的' },
    { label: 'give away', bold: true, explain: '泄露，走漏风声' },
    { label: 'reveal', bold: true, explain: '揭露，揭示' },
    { label: 'give out', bold: true, explain: '宣布，发布' },
    { label: 'disclose', bold: true, explain: '透露，公开' },
    { label: 'generate', bold: true, explain: '生成' },
    { label: 'manufacture', bold: true, explain: '大量制造，批量生产' },
    { label: 'generosity', bold: true, explain: '慷慨' },
    { label: 'kindness', bold: false, explain: '仁慈，善良' },
    { label: 'charity', bold: true, explain: '慈善机构' },
    { label: 'get back', bold: false, explain: '取回，拿回' },
    { label: 'retrieve', bold: true, explain: '挽回，恢复' },
    { label: 'get over', bold: false, explain: '克服，恢复' },
    { label: 'overcome', bold: true, explain: '克服，战胜' },
    { label: 'give space', bold: false, explain: '' },
    { label: 'make way for', bold: false, explain: ' 为….腾出空间' },
    { label: 'good ties', bold: true, explain: '良好关系' },
    { label: 'well relationship', bold: true, explain: '良好关系' },
    { label: 'gorgeous', bold: true, explain: '华丽的' },
    { label: 'habitat', bold: true, explain: '栖息地' },
    { label: 'territory', bold: false, explain: '领土，领地' },
    { label: 'incredible', bold: true, explain: '难以置信的' },
    { label: 'unbelievable', bold: false, explain: '难以置信的' },
    { label: 'caught', bold: false, explain: '被捕捉' },
    { label: 'hazardous', bold: true, explain: '危险的' },
    { label: 'jeopardize', bold: true, explain: '危及到' },
    { label: 'endanger', bold: true, explain: '置于危险中' },
    // { label: 'held back', bold: false, explain: '抑制' },
    // { label: 'suppress', bold: false, explain: '镇压' },
    // { label: 'curb', bold: false, explain: '抑制' },
    // { label: 'restrain', bold: true, explain: '抑制' },
    // { label: 'highlight', bold: false, explain: '高潮，亮点' },
    // { label: 'climax', bold: false, explain: '高潮' },
    // { label: 'hit', bold: false, explain: '打击' },
    // { label: 'strike', bold: false, explain: '打击，攻击' },
    // { label: 'hesitation', bold: true, explain: '犹豫' },
    // { label: 'hold back', bold: false, explain: '犹豫' },
    // { label: 'humiliate', bold: false, explain: '羞耻' },
    // { label: 'disgraceful', bold: true, explain: '丢人的' },
    // { label: 'identical with', bold: true, explain: '与...相同的' },
    // { label: 'exactly alike', bold: true, explain: '完全相同' },
    // { label: 'ignored', bold: true, explain: '忽视' },
    // { label: 'neglect', bold: true, explain: '忽视' },
    // { label: 'overlook', bold: false, explain: '忽视' },
    // { label: 'negligible', bold: true, explain: '微不足道的' },
    // { label: 'imbalanced', bold: false, explain: '不平衡的' },
    // { label: 'uneven', bold: false, explain: '不均匀的' },
    // { label: 'immortal', bold: true, explain: '不朽的' },
    // { label: 'eternal', bold: false, explain: '永恒的' },
    // { label: 'imposing', bold: true, explain: '威风的，壮观的' },
    // { label: 'impressive', bold: false, explain: '令人印象深刻的' },
    // { label: 'in agreement (accordance)with', bold: true, explain: '与.一致' },
    // { label: 'in line with', bold: true, explain: '与..一致' },
    // { label: 'in contrast to', bold: false, explain: '与..形成对比' },
    // { label: 'as opposed to', bold: true, explain: '与...相对' },
    // { label: 'in earnest', bold: true, explain: '认真地，诚恳地' },
    // { label: 'resolutely', bold: false, explain: '坚定地，坚决地' },
    // { label: 'in practical terms', bold: true, explain: '在实际层面上' },
    // { label: 'in effect', bold: true, explain: '实际上' },
    // { label: 'in fact', bold: true, explain: '事实上' },
    // { label: 'virtually', bold: true, explain: '几乎' },
    // { label: 'literally', bold: true, explain: '确切地说' },
    // { label: 'practically', bold: true, explain: '几乎' },
    // { label: 'in terms of', bold: false, explain: '关于，就...而言' },
    // { label: 'with regard to ', bold: false, explain: '对于，就...而言' },
    // { label: 'in no case', bold: true, explain: '被捕捉' },
    // { label: 'under no circumstances ', bold: true, explain: '任何情况下都不能.' },
    // { label: 'in the neighborhood of', bold: true, explain: '接近，大约' },
    // { label: 'approximately', bold: true, explain: '大约地' },
    // { label: 'in vain', bold: true, explain: '徒劳的，白费力气' },
    // { label: 'ineffectively', bold: true, explain: '无效地' },
    // { label: 'incentive', bold: true, explain: '激励' },
    // { label: 'stimuli', bold: true, explain: '刺激' },
    // { label: 'motive', bold: false, explain: '动机' },
    // { label: 'incidence', bold: true, explain: '发生率' },
    // { label: 'occurrence', bold: false, explain: '发生' },
    // { label: 'frequency', bold: true, explain: '频率' },
    // { label: 'rate', bold: true, explain: '率' },
    // { label: 'indecent', bold: true, explain: '猥琐的' },
    // { label: 'nasty', bold: false, explain: '恶心的，令人不悦的' },
    // { label: 'insult', bold: true, explain: '侮辱' },
    // { label: 'industrious', bold: true, explain: '勤勉的，勤劳的' },
    // { label: 'diligent', bold: true, explain: '勤奋的，用心的' },
    // { label: 'influence', bold: true, explain: '影响' },
    // { label: 'impact on ', bold: false, explain: '影响' },
    // { label: 'sway', bold: false, explain: '影响' },
    // { label: 'initiate', bold: true, explain: '发起，开始' },
    // { label: 'initiative', bold: true, explain: '被捕捉' },
    // { label: 'launch', bold: true, explain: '推向，开始' },
    // { label: 'inquiry', bold: false, explain: '询问，调查' },
    // { label: 'investigation', bold: true, explain: '调查，研究' },
    // { label: 'detect', bold: false, explain: '察觉' },
    // { label: 'insert', bold: true, explain: '插入 ' },
    // { label: 'integrate', bold: true, explain: '整合，融合' },
    // { label: 'incorporate', bold: true, explain: '合并，纳入' },
]

export default vocabularyArray4
