import {Vocabulary} from "../types/types.ts";


const vocabularyArray2: Vocabulary[] = [
    {label: 'feature', bold: false, explain: 'n.特征 vt.以...为特色'},
    {label: 'character', bold: false, explain: 'n.特色；品质'},
    // 吹他
    {label: 'trait', bold: false, explain: 'n.特质'},
    {label: 'attribute', bold: false, explain: 'n.属性；特征'},
    {label: 'reputation', bold: false, explain: 'n.名声，声望'},
    {label: 'fame', bold: false, explain: 'n.名誉，名气'},
    {label: 'renown', bold: false, explain: 'n.名誉，声誉'},
    {label: 'merit', bold: false, explain: 'n.优点；美德；价值'},
    {label: 'goodness', bold: false, explain: 'n.善良；优良；美德'},
    {label: 'advantage', bold: false, explain: 'n.优点，优势'},
    {label: 'virtue', bold: false, explain: 'n.美德，优点'},
    {label: 'good qualities', bold: false, explain: '优点'},
    {label: 'shortcoming', bold: false, explain: 'n.缺点；短处'},
    {label: 'defect', bold: false, explain: 'n.缺陷'},
    {label: 'flaw', bold: false, explain: 'n.缺陷；瑕疵；缺点'},
    {label: 'fault', bold: false, explain: 'n.缺点；弱点'},
    {label: 'weakness', bold: false, explain: 'n.弱点；较弱'},
    {label: 'imperfection', bold: false, explain: 'n.不完美'},
    {label: 'inertia', bold: false, explain: 'n.懒惰,惰性,惯性'},
    {label: 'laziness', bold: false, explain: 'n.懒散;怠惰;徐缓'},
    {label: 'idleness', bold: false, explain: 'n.懒惰;闲散;安逸'},
    {label: 'talent', bold: false, explain: 'n.天赋，才能，天赏；人才'},
    {label: 'aptitude', bold: false, explain: 'n.天资；天赋'},
    {label: 'genius', bold: false, explain: 'n.天赋；天才'},
    {label: 'gift', bold: false, explain: 'n.天赋；礼物；赠品'},
    {label: 'facility', bold: false, explain: 'n.才能，天赋'},
    {label: 'competence', bold: false, explain: 'n.能力，胜任'},
    {label: 'ability', bold: false, explain: 'n.能力'},
    {label: 'capability', bold: false, explain: 'n.能力，才能'},
    // 可怕-city
    {label: 'capacity', bold: false, explain: 'n.能力，才能'},
    {label: 'intelligence', bold: false, explain: 'n.智力，理解力'},
    // 维他命
    {label: 'wit', bold: false, explain: 'n.机智；风趣；智力'},
    {label: 'wisdom', bold: false, explain: 'n.智慧；才智'},
    {label: 'mature', bold: false, explain: 'adj.成熟的，考虑周到的 v.成熟，长成'},
    {label: 'adult', bold: false, explain: 'adj.成年的，发育成熟的'},
    {label: 'full-grown', bold: false, explain: 'adj.成熟的，长成的'},
    {label: 'grown-up', bold: false, explain: 'adj.成长的，成熟的'},
    {label: 'full-blown', bold: false, explain: 'adj.成年的，发育成熟的'},
    {label: "attractive", bold: false, explain: "adj.有吸引力的"},
    {label: "enticing", bold: false, explain: "adj.有诱惑力的",},
    // 蔡明
    {label: "charming", bold: false, explain: "adj.令人着迷的",},
    {label: "catching", bold: false, explain: "adj.有感染力",},
    {label: "enchanting", bold: false, explain: "adj.迷人的"},
    // 粉丝来听
    {label: "fascinating", bold: false, explain: "adj.迷人的"},
    {label: "elegant", bold: false, explain: "adj.优雅的，端庄的"},
    {label: "refined", bold: false, explain: "adj.有礼悦的；优雅的"},
    {label: "graceful", bold: false, explain: "adj.优雅的，优美的",},
    {label: "polite", bold: false, explain: "adj.有礼貌的，有教养的"},
    {label: "considerate", bold: false, explain: "adj.考虑周到的，体谅的"},
    {label: "deliberate", bold: false, explain: "adj.深思熟虑的"},
    {label: "thoughtful", bold: false, explain: "adj.考虑周到的"},
    // 的士贵的
    {label: "discreet", bold: false, explain: "adj.谨慎的，小心的"},
    {label: "careful", bold: false, explain: "adj.谨慎的；仔细的"},
    {label: "prudent", bold: false, explain: "adj.谨慎的；慎重的"},
    // 烤蛇食
    {label: "cautious", bold: false, explain: "adj.谨慎的；小心的"},
    {label: "careless", bold: false, explain: "adj. 粗心大意的"},
    {label: "reckless", bold: false, explain: "adj. 鲁莽的、不计后果的"},
    // 热死
    {label: "rash", bold: false, explain: "adj. 鲁莽的；轻率的"},
    {label: "imprudent", bold: false, explain: "adj. 鲁莽的"},
    {label: "thoughtless", bold: false, explain: "adj. 欠考虑的"},
    {label: "awkward", bold: false, explain: "adj. 笨拙的；尴尬的"},
    // 肯老母鸡的
    {label: "clumsy", bold: false, explain: "adj. 笨拙的；不灵巧的"},
    {label: "unhandy", bold: false, explain: "adj. 笨拙的；难处理的"},
    {label: "foolish", bold: false, explain: "adj. 愚笨的，愚蠢的"},
    {label: "clever", bold: false, explain: "adj. 聪明的，伶俐的；机智的，机巧的"},
    {label: "wise", bold: false, explain: "adj. 明智的；充满智慧的"},
    {label: "bright", bold: false, explain: "adj. 聪明的；明亮的"},
    {label: "intellectual", bold: false, explain: "adj. 才智超群的"},
    {label: "intelligent", bold: false, explain: "adj. 聪明的"},
    {label: "smart", bold: false, explain: "adj. 聪明的"},
    {label: "cute", bold: false, explain: "adj. 聪明，伶俐的"},
    {label: "suspicious", bold: false, explain: "adj. 可疑的，多疑的，疑心的"},
    {label: "distrustful", bold: false, explain: "adj. 可疑的"},
    {label: "doubtful", bold: false, explain: "adj. 可疑的；怀疑的"},
    // 都不是
    {label: "dubious", bold: false, explain: "adj. 可疑的，有疑惑的"},
    {label: "questionable", bold: false, explain: "adj. 可疑的"},
    {label: "formidable", bold: false, explain: "adj. 可怕的；(形状)巨大的；使人敬畏的"},
    {label: "frightful", bold: false, explain: "adj. 可怕的；极坏的"},
    // 好惹不
    {label: "horrible", bold: false, explain: "adj. 极坏的；恐怖的"},
    {label: "terrible", bold: false, explain: "adj. 可怕的"},
    // 啊？什么
    {label: "awesome", bold: false, explain: "adj. 可怕的，让人惊叹的"},
    {label: "fearful", bold: false, explain: "adj. 吓人的，可怕的"},
    {label: "evil", bold: false, explain: "adj. 邪恶的，坏的 n. 罪恶；祸害"},
    // 死拜特
    {label: "spiteful", bold: false, explain: "adj. 恶毒的；恶意的"},
    {label: "wicked", bold: false, explain: "adj. 邪恶的；缺德的"},
    {label: "evil-minded", bold: false, explain: "adj. 恶毒的；心地邪恶的"},
    {label: "sinful", bold: false, explain: "adj. 邪恶的；不道德的"},
    {label: "vicious", bold: false, explain: "adj. 恶毒的"},
    // 马丽莎死
    {label: "malicious", bold: false, explain: "adj. 恶意的"},
    {label: "eccentric", bold: false, explain: "adj. 奇怪的，反常的 n. 古怪的人"},
    {label: "odd", bold: false, explain: "adj. 古怪的；奇怪的"},
    {label: "queer", bold: false, explain: "adj. 奇怪的；反常的"},
    {label: "strange", bold: false, explain: "adj. 奇怪的；奇特的"},
    // 皮裤脸
    {label: "peculiar", bold: false, explain: "adj. 奇怪的"},
    {label: "weird", bold: false, explain: "adj. 奇怪的；诡异的"},
    {label: "bizarre", bold: false, explain: "adj. 奇异的，古怪的"},
    {label: "slender", bold: false, explain: "adj. 苗条的，纤细的"},
    {label: "slim", bold: false, explain: "adj. 苗条的，纤细的"},
    {label: "lean", bold: false, explain: "adj. 瘦的，健美的"},
    {label: 'disaster', bold: false, explain: "灾难"},
    {label: "misfortune", bold: false, explain: "n. 灾祸, 灾难"},
    {label: "tragedy", bold: false, explain: "n. 悲剧, 灾难"},
    {label: "catastrophe", bold: false, explain: "n. 灾难, 灾难"},
    {label: "confront", bold: true, explain: "vt. (with) 遭遇; 对抗"},
    {label: "face", bold: false, explain: "vt. 面临 n. 脸, 表面"},
    // 硬抗他
    {label: "encounter", bold: true, explain: "v. 遭遇"},
    {label: "starvation", bold: true, explain: "n. 饥饿, 挨饿"},
    {label: "famine", bold: false, explain: "n. 饥荒; 匮乏, 短缺"},
    {label: "hunger", bold: true, explain: "n. 饥饿; 饥饿感"},
    {label: "surplus", bold: true, explain: "adj. 过剩的, 剩余的 n. 过剩; 剩余"},
    {label: "excessive", bold: false, explain: "adj. 过度的, 极度的"},
    {label: "remainder", bold: true, explain: "n. 剩余物"},
    {label: "rest", bold: false, explain: "n. 剩余部分; 余下的人"},
    {label: "remains", bold: true, explain: "n. 剩余物; 残留物"},
    {label: "uniform", bold: true, explain: "相同的"},
    {label: "identical", bold: true, explain: "adj. 相同的"},
    {label: "same", bold: false, explain: "adj. 相同的；同一的"},
    {label: "duplicate", bold: true, explain: "adj. 完全一样的"},
    {label: "diverse", bold: true, explain: "adj. 不一样的，相异的"},
    {label: "various", bold: true, explain: "adj. 各种各样的"},
    {label: "different", bold: false, explain: "adj. 不同的"},
    {label: "eligible", bold: true, explain: "adj. 合适的；合格的"},
    {label: "suitable", bold: true, explain: "adj. 合适的；适宜的"},
    {label: "appropriate", bold: true, explain: "adj. 合适的"},
    {label: "qualified", bold: true, explain: "adj. 合适的"},
    {label: "fit", bold: false, explain: "adj. 合适的"},
    {label: "abnormal", bold: true, explain: "adj. 不正常的；变态的；不规则的"},
    {label: "odd", bold: true, explain: "adj. 古怪的；奇怪的"},
    {label: "irregular", bold: true, explain: "adj. 不寻常的"},
    {label: "unusual", bold: true, explain: "adj. 不寻常的"},
    {label: "absurd", bold: true, explain: "adj. 荒谬的；可笑的 n. 荒诞"},
    {label: "ridiculous", bold: false, explain: "adj. 荒谬的"},
    // 犀利
    {label: "silly", bold: false, explain: "adj. 愚蠢的；不明事理的"},
    {label: "inevitable", bold: true, explain: "adj. 必然的，不可避免的"},
    {label: "inescapable", bold: false, explain: "adj. 不可避免的"},
    {label: "unavoidable", bold: false, explain: "adj. 不可避免的"},
    {label: "doomed", bold: false, explain: "adj. 注定的；命定的"},
    {label: "trivial", bold: true, explain: "adj. 不重要的，琐碎的"},
    {label: "unimportant", bold: false, explain: "adj. 不重要的"},
    {label: "insignificant", bold: false, explain: "adj. 不重要的"},
    {label: "potential", bold: true, explain: "adj. 可能的，潜在的 n. 潜能，能力"},
    {label: "possible", bold: false, explain: "adj. 可能的；可能"},
    {label: "likely", bold: false, explain: "adj. 可能的；预料的"},
    {label: "probable", bold: false, explain: "adj. 可能的"},
    {label: "precise", bold: true, explain: "adj. 确切的；准确的"},
    // IQ right就
    {label: "accurate", bold: false, explain: "adj. 精确的"},
    // 一刻再刻的
    {label: "exact", bold: false, explain: "adj. 准确的；精确的"},
    {label: "successive", bold: false, explain: "adj. 连续的，依次的"},
    {label: "continuous", bold: false, explain: "adj.连续的"},
    {label: "uninterrupted", bold: false, explain: "adj.连续的"},
    // 看谁可替我
    {label: "consecutive", bold: false, explain: "adj.连续的"},
    {label: "frequent", bold: true, explain: "adj.频繁的"},
    {label: "often", bold: false, explain: "adv.经常；往往"},
    // 肯定牛
    {label: "continual", bold: false, explain: "adj.频繁的"},
    {label: "authentic", bold: true, explain: "adj.真实的；可靠的，可信的"},
    {label: "actual", bold: false, explain: "adj.真实的；实际的"},
    {label: "genuine", bold: false, explain: "adj.真正的"},
    {label: "true", bold: false, explain: "adj.符合事实的；确实的"},
    {label: "real", bold: false, explain: "adj.真实的；真正的"},
    {label: "typical", bold: true, explain: "adj.典型的"},
    {label: "representation", bold: false, explain: "adj.典型的"},
    {label: "classic", bold: false, explain: "adj.典型的，有代表性的"},
    {label: "numerous", bold: true, explain: "adj.众多的，大批的，无数的"},
    {label: "abundant", bold: false, explain: "adj.大量的"},
    {label: "mass", bold: false, explain: "adj.许多的；许多的"},
    { label: "comprehensive", bold: true, explain: "adj.全面的" },
    // 因太饿
    { label: "entire", bold: true, explain: "adj.全部的" },
    { label: "total", bold: false, explain: "adj.全部的；总的" },
    { label: "faultless", bold: true, explain: "adj.完美的；无缺点的" },
    { label: "perfect", bold: false, explain: "adj.完美的；完备的" },
    { label: "flawless", bold: false, explain: "adj.完美的" },
    // 易拉不弱他
    { label: "elaborate", bold: true, explain: "adj.精致的 vt.精心制作" },
    { label: "delicate", bold: false, explain: "adj.精致的；精美的" },
    { label: "fine", bold: false, explain: "adj.精致的，华贵的" },
    { label: "stern", bold: true, explain: "adj.严厉的；苛刻的" },
    { label: "severe", bold: false, explain: "adj.严厉的；严重的；严峻的" },
    { label: "strict", bold: false, explain: "adj.严厉的；严格的" },
    { label: "rigorous", bold: true, explain: "adj.严格的；苛刻的" },
    { label: "solemn", bold: true, explain: "adj.庄严的；隆重的" },
    { label: "grave", bold: false, explain: "adj.严肃的；庄严的" },
    { label: "majestic", bold: false, explain: "adj.威严的" },
    { label: "dignified", bold: false, explain: "adj.庄严的；高贵的" },
    { label: "ancient", bold: true, explain: "adj.古老的；古代的" },
    { label: "old", bold: false, explain: "adj.古老的；破旧的" },
    { label: "aged", bold: false, explain: "adj.年老的，年迈的" },
    { label: "faulty", bold: true, explain: "adj.有错误的，有缺点的" },
    { label: "false", bold: false, explain: "adj.错误的；不正确的" },
    { label: "erroneous", bold: false, explain: "adj.错误的" },
    { label: "mistaken", bold: false, explain: "adj.错误的" },
    { label: "incorrect", bold: false, explain: "adj.错误的" },
    { label: "wrong", bold: false, explain: "adj.错误的；不对的" },
    { label: "mysterious", bold: true, explain: "adj.神秘的，难以理解的" },
    // 为儿的
    { label: "weird", bold: false, explain: "adj.神秘的；奇怪的" },
    { label: "magic", bold: false, explain: "adj.神奇的" },
    // 一门死
    { label: "immense", bold: true, explain: "adj.巨大的，广大的" },
    { label: "enormous", bold: false, explain: "adj.巨大的" },
    // 哥 i ant
    { label: "giant", bold: false, explain: "adj.巨大的；特大的" },
    { label: "gigantic", bold: false, explain: "adj.巨大的" },
    { label: "great", bold: false, explain: "adj.伟大的；巨大的" },
    { label: "huge", bold: false, explain: "adj.巨大的；极多的" },
    { label: "massive", bold: false, explain: "adj.大量的；巨大的" },
    // 挖死他
    { label: "vast", bold: false, explain: "adj.巨大的；辽阔的" },
    { label: "tremendous", bold: false, explain: "adj.极大的" },
    { label: "medium", bold: true, explain: "adj. 中等的，适中的 n. 中间；媒介" },
    { label: "middle", bold: false, explain: "adj. 中间的；中等的" },
    { label: "moderate", bold: false, explain: "adj. 中等的" },
    { label: "integral", bold: true, explain: "adj. 完整的" },
    { label: "whole", bold: false, explain: "adj. 全部的，整个的" },
    { label: "entire", bold: false, explain: "adj. 全部的；完整的" },
    // in tank
    { label: "intact", bold: false, explain: "adj. 完好无损的" },
    { label: "complete", bold: false, explain: "adj. 全部的" },
    // kan size
    { label: "concise", bold: true, explain: "adj. 简明的，简洁的" },
    // 不理父
    { label: "brief", bold: false, explain: "adj. 简明的；短暂的" },
    { label: "straightforward", bold: false, explain: "adj. 简单的，易懂的" },
    { label: "simple", bold: false, explain: "adj. 简单的，简明的" },
    { label: "obvious", bold: true, explain: "adj. 显著的，显而易见的" },
    { label: "striking", bold: false, explain: "adj. 引人注目的" },
    { label: "apparent", bold: false, explain: "adj. 显然的" },
    { label: "noticeable", bold: false, explain: "adj. 值得注意的" },
    // 爱，为等他
    { label: "evident", bold: false, explain: "adj. 显而易见的" },
    { label: "conspicuous", bold: false, explain: "adj. 明显的" },
    { label: "perpetual", bold: true, explain: "adj. 永久的" },
    // 一头老
    { label: "eternal", bold: false, explain: "adj. 永久的；不朽的" },
    // 泼墨弄他
    { label: "permanent", bold: false, explain: "adj. 永久的" },
    { label: "forever", bold: false, explain: "adv. 长期的，永久的" },
    { label: "everlasting", bold: false, explain: "adj. 永恒的" },
    { label: "momentary", bold: true, explain: "adj. 短暂的，瞬间的" },
    { label: "immediate", bold: false, explain: "adj. 即刻的" },
    { label: "quick", bold: false, explain: "adj. 持续时间短的，快的" },
    { label: "sudden", bold: false, explain: "adj. 突然的；忽然的" },
    { label: "instant", bold: false, explain: "n. 瞬间 adj. 立刻的" },
    { label: "swift", bold: true, explain: "adj. 快的，迅速的" },
    { label: "speedy", bold: false, explain: "adj. 迅速的；尽快的" },
    // 浮力的
    { label: "fleet", bold: false, explain: "adj. 快速的" },
    { label: "fast", bold: false, explain: "adj. 快速的；快的" },
    { label: "quick", bold: false, explain: "adj. 快的；迅速的" },
    // rabbit
    { label: "rapid", bold: false, explain: "adj. 迅速的；快速的" },
    // 废了他
    { label: "faint", bold: true, explain: "adj. 模糊的；虚弱的" },
    // 地墓
    { label: "dim", bold: false, explain: "adj. 模糊不清的；忧愁的" },
    { label: "cloudy", bold: false, explain: "adj. 多云的；模糊不清的" },
    { label: "foggy", bold: false, explain: "adj. 有雾的；模糊的" },
    { label: "obscure", bold: false, explain: "adj. 模糊的" },
    { label: "dusty", bold: false, explain: "adj. 灰暗的；无光泽的" },
    { label: "misty", bold: false, explain: "adj. 不明晰的" },
    { label: "blurry", bold: false, explain: "adj. 模糊不清的" },
    { label: "vague", bold: false, explain: "adj. 模糊的；不清楚的" }

]
vocabularyArray2.forEach(item => {
    item.bold = false
})
export default vocabularyArray2
