import {Vocabulary} from "./types";

const vocabularyArray3: Vocabulary[] = [
    { label: 'convey', bold: false, explain: '传达' },
    { label: 'deliver', bold: true, explain: '交付，运输' },
    { label: 'transport', bold: false, explain: '运输' },
    { label: 'convicted', bold: true, explain: '被定罪的' },
    { label: 'condemned', bold: true, explain: '被严厉谴责的' },
    { label: 'count on', bold: false, explain: '依靠' },
    { label: 'lean on', bold: true, explain: '依靠' },
    { label: 'coordinate', bold: true, explain: '协调' },
    { label: 'regulate', bold: true, explain: '规范' },
    { label: 'create', bold: false, explain: '创造' },
    { label: 'produce', bold: false, explain: '生产' },
    { label: 'generate', bold: true, explain: '传达' },
    { label: 'invent', bold: false, explain: '发明' },
    { label: 'craft', bold: false, explain: '制作 ' },
    { label: 'criteria', bold: true, explain: '标准' },
    { label: 'standards', bold: false, explain: '标准' },
    { label: 'critical', bold: true, explain: '关键的' },
    { label: 'crucial', bold: true, explain: '关键的' },
    { label: 'criticize', bold: false, explain: '批评' },
    { label: 'find fault with', bold: false, explain: '挑剔' },
    { label: 'current', bold: false, explain: '' },
    { label: 'latest', bold: false, explain: '最新的' },
    { label: 'damp', bold: false, explain: '潮湿的' },
    { label: 'moist', bold: true, explain: '潮湿的' },
    { label: 'deadly', bold: false, explain: '致命的' },
    { label: 'fatal', bold: false, explain: '致命的' },
    { label: 'deception', bold: true, explain: '欺骗' },
    { label: 'cheating', bold: true, explain: '作弊' },
    { label: 'fraud', bold: true, explain: '欺诈' },
    { label: 'decisively', bold: true, explain: '果断地' },
    { label: 'resolutely', bold: true, explain: '坚决地' },
    { label: 'stand firm', bold: false, explain: '坚守，坚定' },
    { label: 'decorate', bold: false, explain: '传达' },
    { label: 'beautify', bold: false, explain: '传达' },
    { label: 'decreased', bold: true, explain: '减少的' },
    { label: 'diminished', bold: false, explain: '下降的' },
    // { label: 'convey', bold: false, explain: '传达' },
    // { label: 'convey', bold: false, explain: '传达' },
    // { label: 'convey', bold: false, explain: '传达' },
]
export default vocabularyArray3
