import {Vocabulary} from "@/types/types.ts";

const vocabulary6: Vocabulary[] = [
    {label: 'exquisite', bold: false, explain: '精美的'},
    {label: 'aggressively', bold: false, explain: '积极地'},
    {label: 'vigorously', bold: false, explain: '精神旺盛地，有力地'},
    {label: 'provoke', bold: true, explain: '激起，引起'},
    {label: 'clause', bold: true, explain: '条款'},
    {label: 'legislative', bold: true, explain: '立法的'},
    {label: 'Provision', bold: true, explain: '规定'},
    {label: 'clues', bold: false, explain: '线索'},
    {label: 'hints', bold: false, explain: '提示'},
    {label: 'combat', bold: false, explain: '战斗'},
    {label: 'comply with', bold: true, explain: '遵守'},
    {label: 'subsidy', bold: false, explain: '补贴'},
    {label: 'compulsory', bold: false, explain: '强制的'},
    {label: 'substitute', bold: true, explain: '替代品'},
    {label: 'motivate', bold: true, explain: '激发'},
    {label: 'stimulate', bold: true, explain: '刺激'},
    {label: 'estimation', bold: false, explain: '估计'},
    {label: 'exclusively', bold: true, explain: '专门地'},
    {label: 'implement', bold: false, explain: '实施'},
    {label: 'carry out', bold: false, explain: '执行'},
    {label: 'formidable', bold: true, explain: '可怕的、令人敬畏的'},
    {label: 'identical with', bold: true, explain: '与...相同的'},
    {label: 'negligible', bold: true, explain: '微不足道的'},
    {label: 'immortal', bold: true, explain: '不朽的'},
    {label: 'eternal', bold: false, explain: '永恒的'},
    {label: 'imposing', bold: true, explain: '威风的，壮观的'},
    {label: 'incentive', bold: true, explain: '激励'},
    {label: 'stimuli', bold: true, explain: '刺激'},
    {label: 'motive', bold: false, explain: '动机'},
    { label: 'incidence', bold: true, explain: '发生率' },
    { label: 'indecent', bold: true, explain: '猥琐的' },
    { label: 'nasty', bold: false, explain: '恶心的，令人不悦的' },
    { label: 'insult', bold: true, explain: '侮辱' },
    { label: 'initiative', bold: true, explain: '措施，倡议；主动性，积极性；主动权' },
    { label: 'detect', bold: false, explain: '察觉' },
    { label: 'institute', bold: true, explain: '建立，创立' },
    { label: 'establish', bold: true, explain: '建立' },
    { label: 'intimate', bold: true, explain: '亲密的' },
    { label: 'permanent', bold: true, explain: '永久的' },
    { label: 'sustainable', bold: true, explain: '可持久的' },
    { label: 'perpetuate', bold: true, explain: '永久化，使永久' },
    { label: 'legitimate', bold: false, explain: '合法的，合理的' },
    { label: 'entitled', bold: true, explain: '有权的' },
    { label: 'eligible', bold: true, explain: '有资格的' },
    { label: 'qualified', bold: true, explain: '具备资格的' },
    { label: 'prospect', bold: true, explain: '前景，展望' },
    { label: 'specific', bold: true, explain: '具体的' },
    { label: 'concrete', bold: true, explain: '具体的' },
    { label: 'appropriate', bold: true, explain: '恰当的' },
    { label: 'deposit', bold: true, explain: '存放，存款' },
    { label: 'tolerate', bold: true, explain: '容忍，忍受' },
    { label: 'saturate', bold: false, explain: '浸湿，湿透' },
    { label: 'undermine', bold: true, explain: '破坏，消弱' },
    { label: 'reluctant', bold: true, explain: '勉其难' },
    { label: 'typically', bold: true, explain: '通常地' },
    { label: 'perspective', bold: true, explain: '观点' },
    { label: 'certainly', bold: false, explain: '必然的' },
    { label: 'inevitable', bold: true, explain: '必然的' }
]
export default vocabulary6
