import {Vocabulary} from "@/types/types.ts";

const vocabularyArray5: Vocabulary[] = [
  { label: 'pledge', bold: false, explain: '誓言，承诺' },
  { label: 'pose', bold: true, explain: '提出，引起' },
  { label: 'raise', bold: true, explain: '提出，提高' },
  { label: 'poverty', bold: true, explain: '贫困' },
  { label: 'needy', bold: true, explain: '贫困的' },
  { label: 'impoverish', bold: false, explain: '使贫困' },
  { label: 'practice', bold: false, explain: '实践，练习' },
  { label: 'practicality', bold: true, explain: '实用性，实际性' },
  { label: 'precious', bold: true, explain: '珍贵的' },
  { label: 'valuable', bold: false, explain: '有价值的' },
  { label: 'precision', bold: true, explain: '精度，精确度' },
  { label: 'accuracy', bold: true, explain: '准确性，准确度' },
  { label: 'predict', bold: true, explain: '预测，预言' },
  { label: 'foreseen', bold: true, explain: '预见，预料' },
  { label: 'forecast', bold: true, explain: '预报' },
  { label: 'present', bold: true, explain: '礼物、呈现、目前的' },
  { label: 'pressing', bold: true, explain: '紧迫的，急迫的' },
  { label: 'urgent', bold: true, explain: '紧急的，急迫的' },
  { label: 'presume', bold: true, explain: '假设，推测' },
  { label: 'assume', bold: true, explain: '假定，假设' },
  { label: 'suppose', bold: true, explain: '假定的，应该是' },
  { label: 'imagine', bold: false, explain: '想像，设想' },
  { label: 'primarily', bold: true, explain: '主要地' },
  { label: 'mainly', bold: false, explain: '主要地' },
  { label: 'chiefly', bold: true, explain: '首席地' },
  { label: 'proceed', bold: false, explain: '进行，继续' },
  { label: 'conduct', bold: false, explain: '进行，执行，指导' },
  { label: 'produce', bold: false, explain: '生产，制造' },
  { label: 'turn out', bold: true, explain: '结果是、证明是' },
  { label: 'profound', bold: false, explain: '深远的，深奧的' },
  { label: 'penetrating', bold: false, explain: '敏锐的，洞察的' },
]
export default vocabularyArray5
